- README.md
- example/microphone/index.html
- plugin/wavesurfer.microphone.js
- src/drawer.js
- src/wavesurfer.js
This fixes #323 and adds some improvements to the microphone plugin.
> fix destroy wrapper issue

- plugin/wavesurfer.regions.js
Attempt at a fix. Seems to work pretty well for me. I don't use resizable regions though.
> fix for issue #321

- Makefile
@license to help the comment from being stripped by scripts.  Helpful to know license when found randomly in a project (for lawyer's sake).
> Makefile + @license

- plugin/wavesurfer.minimap.js
The regions are shown in the minimap and the minimap shows clearly which part of the wave is showing above. You can see an example [here](http://development.wavesurfer-bitbucket.divshot.io/) and the example code  [here](https://github.com/RocAlayo/example-wavesurfer.js-minimap)
> Minimap new functionalities (overview and regions support)

- example/spectrogram/app.js
- example/spectrogram/index.html
- plugin/wavesurfer.spectrogram.js
This PR is created to replace #186.
> add spectrogram plugin

- plugin/wavesurfer.regions.js
- src/drawer.js
I believe this problem was created by merging one of my last Pull Request. That or it was entirely my fault :P
Either way here is the patch :)
> Corrects region width problem

- src/drawer.js
> fix issue when calling destroy() twice

- src/webaudio.js
@naomiaro could you review this PR, please?
> resolves #357; stop cursor on scheduled pause

- src/webaudio.js
> return 0 when buffer is undefined or null

- plugin/wavesurfer.microphone.js
> microphone plugin: loadDecodedBuffer doesn't empty anymore

- plugin/wavesurfer.regions.js
> Correct param assignments on region update

- index.html
> fix broken download url (#390)

- .travis.yml
- Gruntfile.js
- package.json
- plugin/wavesurfer.minimap.js
- plugin/wavesurfer.spectrogram.js
- plugin/wavesurfer.timeline.js
refs #409 and #408 
Also includes travis build.
> add jshint task and travis build file

- plugin/wavesurfer.regions.js
I find very useful to add an id to the rendered region, so I can modify it by interacting with other DOM elements.
> Added id to the rendered region

- package.json
Resolves #474 
@thijstriemstra review please.
> License expression syntax

- src/mediaelement.js
Added check if media exists in isPaused mediaelement function, it's useful when we trying stop audio when it was destriyed or not set
> Added check if media exists in isPaused function

- example/angular/index.html
- example/annotation/index.html
- example/audio-element/index.html
- example/elan/index.html
- example/equalizer/index.html
- example/microphone/index.html
- example/panner/index.html
- example/playlist/index.html
- example/spectrogram/index.html
- example/split-channels/index.html
- example/timeline/index.html
- example/zoom/index.html
> Fix broken links and update bootstrap in examples

- example/angular-material/index.html
- example/angular-material/main.css
- example/angular-material/main.js
- example/angular-material/md-player-audio.partial.html
- example/angular-material/md-player.partial.html
- example/angular-material/wavesurfer.directive.js
- index.html
Created AngularJS Material example, the files can be reused in other projects easily.
> squashed commits for angularjs material

- plugin/wavesurfer.regions.js
Fix regarding issue I found https://github.com/katspaugh/wavesurfer.js/issues/598.
Please take a look at it. Not sure that this is the best solution but it works for me
> Fixed region updation error after zoom

- .travis.yml
See https://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade
> Migrate from legacy to container-based Travis infrastructure

- plugin/wavesurfer.spectrogram.js
> spectrogram plugin: fix offline audio context definition for Safari

- example/annotation/index.html
- plugin/wavesurfer.regions.js
Adding disableDragSelection so we can toggle.
we can do a manual call if you prefer, just did this since it's less changes ;)
> Added disableDragSelection

- src/wavesurfer.js
- src/webaudio.js
@cdelguercio I like your idea to load the audio on demand (from #733). I suggest we do it every time peaks are passed with the Web Audio backend.
> Allow pre-decoded peaks with Web Audio

- src/mediaelement.js
fix for https://github.com/katspaugh/wavesurfer.js/issues/543
> fix media element ios issue #543 where peaks didnt draw

- plugin/wavesurfer.regions.js
- src/drawer.js
Per request from @LBPSlava, adding touch support for region moving.
Related to a0464534070c4e6aaaad07883c98b89f114f41f5.
> Add touch support for region moving

- plugin/wavesurfer.spectrogram.js
- plugin/wavesurfer.timeline.js
#762 hello @katspaugh, please help review my pull request. Thanks!
> fix drawer onscoll event override issue by using addEventListener

- src/drawer.js
> 788 - Zooming doesn't clear canvas before redrawing

- src/drawer.multicanvas.js
This PR is a replacement for #785, which caused other issues. The PR pertains to #781.
Instead of dividing the waveform up into equal sizes as I tried in #785, I keep my current apportioning algorithm the same. What changes is that I record a `start` and `end` value against each canvas entry. These values are decimals between 0 and 1, and they represent the location within the waveform.
This allows me to render the correct peak data against each canvas, whereas I previously just divided the peaks evenly amongst the canvases. This was wrong because the last canvas can be much smaller than the other canvases, which screws things up.
Attached is another runnable test with the new fix: [fix-test-2.zip](https://github.com/katspaugh/wavesurfer.js/files/408957/fix-test-2.zip). Could @samih-dev, …
> 781 MultiCanvas Renderer and Zoom - Current Indicator place is changing

- plugin/wavesurfer.timeline.js
Fix for #778, plus a couple of bonus fixes on the side.
I've split this PR into two commits, as I also fixed a separate issue pertaining to width and offset calculation of the last canvas in the timeline.
> 778 - Multicanvas Timeline Zoom Scrolling Issue

- projects/index.html
Added Electro by @jspear29, and Sparkled by yours truly :)
> Add Electro and Sparkled to Projects list

- src/drawer.canvas.js
> 797 Maximum Stack Size Exceeded

- src/drawer.canvas.js
- src/wavesurfer.js
> add exportImage

- CHANGES.md
- Gruntfile.js
> Correct AMD module name for plugins

- src/mediaelement.js
Reverts katspaugh/wavesurfer.js#847
> Revert "Added HTML Variable Preload Attribute"

- CHANGES.md
- src/wavesurfer.js
Add a 'waveform-ready' event, triggered when waveform is drawn with
MediaElement backend.
> New Event: waveform-ready

- src/plugin/elan.js
Some auto-merging apparently broke this.
> Next: Fixes invalid this error in elan plugin by using arrow function

- src/plugin/cursor.js
* Adding comments
* Checking naming consistency
* Checking to see if stuff exists before removing it in the destroy function
* Optimising minified build size
> Next: refactor cursor plugin

- src/wavesurfer.js
create getPlaybackRate method and return playback rate.
> add wavesurfer.getPlaybackRate()

- plugins/index.html
- plugins/minimap.html
create minimap.html plugin page and link to it from the plugins index.html page
> create minimap.html plugin page

- docs/methods.html
I'll merge once pull request #978 is approved
> getVolume method added

- src/wavesurfer.js
added getMute method, useful to have.
> added getMute method,

- docs/methods.html
to be merged once #980 is merged
> add getMute method

- plugin/wavesurfer.minimap.js
add debounce to resize event for minimap plugin
> add debounce to resize/orientationchange event for minimap plugin

- plugin/wavesurfer.spectrogram.js
feature request #810
- create labels parameter (true|false)
- create labels element and canvas
- create labels frequency method loadLabels();
- update createWrapper() method and apply labels feature parameter.
preview:
http://codepen.io/entonbiba/pen/Bpmqrq
> create new labels feature for spectrogram plugin

- CHANGES.md
- bower.json
- package.json
update version and changelogs to 1.3.2
> update to version 1.3.2

- package.json
- src/util/index.js
Analogous to https://github.com/katspaugh/wavesurfer.js/pull/964 on master, exposed [debounce](https://www.npmjs.com/package/debounce) on `util.debounce`
> Next: installed debounce and exposed it in util.debounce

- README.md
* Updated README.md with information about breaking changes in version 2
/
/
/
* Need to think of how to handle the esdoc generation/how to reference it from README.md
> Next: updated README.md with information about upgrading

- .esdoc.json
- example/css/doc.css
- spec/peakcache.spec.js
- spec/plugin-api.spec.js
- spec/util.spec.js
- spec/wavesurfer.spec.js
- src/drawer.js
- src/drawer.multicanvas.js
- src/html-init.js
- src/mediaelement.js
- src/peakcache.js
- src/plugin/cursor.js
- src/plugin/elan.js
- src/plugin/microphone.js
- src/plugin/minimap.js
- src/plugin/regions.js
- src/plugin/spectrogram.js
- src/plugin/timeline.js
- src/util/extend.js
- src/util/observer.js
- src/util/style.js
- src/wavesurfer.js
- src/webaudio.js
* Added complete and consistent (hopefully) jsdoc comments to all functions (in the root library)
* Added typedefs for often used object formats (like parameter objects) and documented them
* Null initialise variables in the constructor function and documented them with jsdoc comments.
* I have tested this and it doesn't cause any problems.
* This is in general a good idea because the javascript engine does not need to break out of the hidden classes cache when properties are added dynamically (within a method) ([Stackoverflow](http://stackoverflow.com/questions/17925726/clearing-up-the-hidden-classes-concept-of-v8))
* Esdoc currently does not support the `@inheritDoc` or automatically inheriting documentation of inherited properties, for this reason I null-initialised them in the child …
> Next: Documentation

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Added a `.github` directory with templates for new issues and PRs (As described [here](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)) so new issues and PRs have more information (and don't require additional questions).
> Added contributing info

- src/drawer.multicanvas.js
@thijstriemstra I added the method which returns the first canvas in mutli-canvas mode. I say we can get each canvas data and put it in an array, then return. The array size might end up being too long for larger audio files. #1011
What do you think about the array solution?
> add getImage method for MultiCanvas

- src/wavesurfer.js
* Added `responsive` parameter to the core library which causes a debounced resize of waveform container.
* Default is `false`
* If it's a number, use it as the debounce timeout
* If it's `truethy` use `100ms` as default
/
/
/
* Feature was discussed here: https://github.com/katspaugh/wavesurfer.js/pull/963
> Next: Responsive parameter (with debounced resize listener)

- docs/options.html
- plugins/index.html
- plugins/playlist.html
@thijstriemstra Merged the last pr before adding this update, multiple tabs open, #1019
added options and events table and formatted the code layout.
> add options and events table to playlist sample 

- _includes/footer.html
- plugins/playlist.html
- remove extra parameters text
- add `audio/mpegurl` to playlistType option
- increase sample height for playlist plugin
> one more change for playlist plugin sample

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- .npmignore
- src/drawer.multicanvas.js
- src/mediaelement.js
- src/plugin/minimap.js
- src/plugin/spectrogram.js
- src/wavesurfer.js
- src/webaudio.js
* This ports hopefully all the (relevant) recent commits on the master branch to the next branch.
* nullified `this.arraybuffer` in `wavesurfer.destroy` to fix memory leak
> Next: Ports from master and bugfixes

- CHANGES.md
- bower.json
- package.json
update to version 1.3.5
+- Add a `getImage` method for MultiCanvas (#1012)
+- Add Playlist plugin (#1018)
+- Add Playlist plugin sample (#1019)
+- Add a new parameter `barHeight` (#1020)
+- Add a `playBackRate` method for MediaElement (#1022)
> update to version 1.3.5

- docs/index.html
- index.html
updated to
//cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.3.5/wavesurfer.min.js
> update js cdn link to 1.3.5

- docs/methods.html
add setMute() method to docs #1041
> add setMute() method to docs

- plugin/wavesurfer.spectrogram.js
fix spectrogram plugin frequency labels position `absolute`
> fix spectrogram plugin frequency labels position

- docs/methods.html
> add exportPCM method to docs

- src/plugin/regions.js
Changed the input of enableDragSelection from boolean (this.params.dragSelection) to list (this.params)
N/A
N/A
N/A
N/A
> Fixed wrong input to enableDragSelection.

- docs/options.html
add `responsive` parameter to options
should be merged after pr #1097
> add responsive parameter to docs

- src/drawer.js
Topic. Same as https://github.com/katspaugh/wavesurfer.js/pull/1115.
> Update drawer.js (same as #1115 except master instead of next)

- src/drawer.multicanvas.js
I accidentally put in this change on https://github.com/katspaugh/wavesurfer.js/pull/1112.
> Add pointerEvents: none to left/right sides: undo zIndex change.

- plugin/wavesurfer.spectrogram.js
> Remove unused argument from Spectrogram#resample

- src/plugin/regions.js
merge 4ee2b29 in `next` branch to fix region updateRender on zoom out.
None
None
None
see #825
> src/plugin/regions.js: fix regions display on zoom out in next

- plugins/regions.html
Hello, I'm new here. I really like this library so I decided to add some documentation. Let me know if the descriptions need changes or if they can be expressed better. I hope to contribute more, just trying to get my feet wet with this PR. Thanks.
> add documentation for region methods

- docs/index.html
- index.html
updates the cdnjs version automatically.
> auto version update for git pages

- src/plugin/timeline.js
Fixed linting issues which broke the build process.
Fixes #1232
> Fix: linting issues

- src/plugin/spectrogram.js
- Fixes formatting issue which shows an error when building the library
/
/
/
- Sorry, this should have been part of #1233
> Fix: formatting issue in spectrogram plugin

- src/mediaelement.js
- src/plugin/microphone.js
- src/plugin/minimap.js
- src/util/extend.js
- src/util/request-animation-frame.js
- src/webaudio.js
Fixes numerous prettier/prettier linting errors
that blocked webpack-dev-server from starting.
Prior to this PR, npm start fails with errors referencing file linting -- specifically,  prettier/prettier.
This PR cleans up the code so linting succeeds.
> Linting fixes to src files

- CHANGES.md
> update changelog for 2.0.1

- CHANGES.md
- src/webaudio.js
> replace deprecated gain.value setter

- CHANGES.md
- src/drawer.multicanvas.js
- src/wavesurfer.js
This uses the existing implementation if the parameter is not supplied, otherwise it uses the user defined value with minimum of pixel ratio.
fixes #1058
> Adding barGap as an optional parameter for drawBar render (Proposal for #1058)

- build-config/fragments/plugins.js
- example/media-session/app.js
- example/media-session/index.html
- example/plugin-system/app.js
- example/plugin-system/index.html
- example/stretcher/app.js
- src/plugin/mediasession.js
Several files have been missing since the v.2.0 beta merge. This PR aims to bring some of them back.
refs #1286
> Restore some missing files

- src/plugin/minimap.js
Finished click event navigation logic in the minimap plugin
fixes #1265
> Fix #1265: Minimap - Attach click event to the wrapper

- .gitignore
- CHANGES.md
- build-config/fragments/common.js
- build-config/fragments/min.js
The version info banner was missing from files in `dist` folder.
> Add version info banner

- src/wavesurfer.js
Add an isReady method to know if the wavesurfer is loaded and ready or not.
Need to be tested
fixes #1333
> Add isReady methods

- CHANGES.md
- bower.json
- package.json
* Bump version to 2.0.5
* Updated changelog to reflect changes
> Release 2.0.5

- CHANGES.md
- src/wavesurfer.js
add new event 'mute'  when the function toggleMute is call and return the mute status
add new event 'volume'  when volume is changed
> two new events 'mute' and 'volume'

- _includes/demo.html
- index.html
- v2/index.html
fixes #1309
~~Blocked by https://github.com/cdnjs/cdnjs/pull/12532~~ (merged)
> Update site for v2

- .gitignore
- _includes/footer.html
- example/audio-element/index.html
- example/audio-element/main.js
- faq/index.html
> Update audio element example

- appveyor.yml
- docs/events.html
- docs/methods.html
- docs/options.html
- plugins/cursor.html
- plugins/microphone.html
- plugins/minimap.html
- plugins/regions.html
- plugins/spectrogram.html
- plugins/timeline.html
> update api docs on website

- src/wavesurfer.js
https://github.com/katspaugh/wavesurfer.js/pull/1396#issuecomment-399906346
> update isReady attribute on destroy

- CHANGES.md
- src/webaudio.js
> use srcObject in setSinkId

- .eslintrc.js
- CHANGES.md
- build-config/fragments/common.js
- spec/wavesurfer.spec.js
- src/wavesurfer.js
> make WaveSurfer version number available

- docs/index.html
- index.html
add protocol for running on local machine
fixes #1447
> update <script src=""> example on website

- build-config/fragments/common.js
- package.json
> use short date format in copyright header

- docs/index.html
- index.html
- plugins/cursor.html
- plugins/microphone.html
- plugins/minimap.html
- plugins/regions.html
- plugins/spectrogram.html
- plugins/timeline.html
> switch to unpkg

- _includes/demo.html
> switch to unpkg cdn on homepage

- plugins/index.html
This is a documentation contribution.
This fixes #1477.
> Add instructions on how to configure a plugin

- projects/index.html
add waveform.al api service link
What this service offers:
- allows to create waveform json audio data and images from audio files that can be used with wavesurfer.js
- no audio files are stored on server, audio json data will be available via cdn
- wavesurfer-js.org is already whitelisted with CORS for unlimited use
You can request features here: #1183
> add waveform.al to projects links

- plugins/microphone.js
> add safari workaround for mic plugin example

- src/plugin/cursor.js
Documents new CursorPluginParams.
No.
No.
No.
The parameters were introduced in #1511.
> plugins: document new CursorPluginParams

- CHANGES.md
- package.json
- src/plugin/spectrogram.js
> spectrogram plugin: properly remove event listeners

- CHANGES.md
- spec/wavesurfer.spec.js
- src/wavesurfer.js
> add backgroundColor option

- src/plugin/cursor.js
> fix cursor's displayTime

- CHANGES.md
- src/plugin/spectrogram.js
> spectrogram plugin: fix event listeners

- src/plugin/spectrogram.js
spectrogram:plugin fix render listener and fix wrapper click handler
> spectrogram:plugin fix render listener and fix wrapper click handler

- faq/index.html
> doc: expand audiowaveform FAQ item

- CHANGES.md
- src/mediaelement.js
> update progress when seeking with HTML media controls

- CHANGES.md
- example/regions/app.js
- example/spectrogram/index.html
- src/plugin/regions.js
> regions plugin: fix ready listener when loading multiple audio files

- .travis.yml
- karma.conf.js
> travis: enable the autoplay policy for Web Audio in Chrome

- CHANGES.md
- package.json
- spec/wavesurfer.spec.js
- src/drawer.multicanvas.js
- src/wavesurfer.js
> add Blob support for exportImage

- CHANGES.md
- src/drawer.canvasentry.js
- src/drawer.multicanvas.js
- src/wavesurfer.js
this feature was broken before.
> disable progress canvas when waveColor and progressColor are identical

- .vscode/launch.json
- README.md
Suggestion on using VS Code - Debugger for Chrome for the development
> configure the VS Code Debugger for the development

- CHANGES.md
- spec/mediaelement.spec.js
- src/mediaelement.js
- src/wavesurfer.js
> mediaelement: fix volume updates

- CHANGES.md
- src/util/ajax.js
- src/wavesurfer.js
> improve documentation for util.ajax

- example/minimap/app.js
- example/minimap/index.html
- example/regions/app.js
- src/plugin/minimap.js
couldn't find a dedicated example so created one.
> examples: add minimap plugin example

- CHANGES.md
- UPGRADE.md
> docs: add upgrade instructions for 3.0

- CHANGES.md
- bower.json
- package.json
> release 3.0.0

- .eslintrc.js
- src/plugin/regions.js
fixes #1713
add regions props isResizing and isDragging to filter events in region-updated listener
> regions plugin: use isResizing and isDragging to filter events in region-updated listener

- CHANGES.md
- src/wavesurfer.js
include complete error object in `fetch` error handler
> improve fetch error messages

- CHANGES.md
- spec/wavesurfer.spec.js
- src/wavesurfer.js
> make sure isReady is true when firing the ready event

- CHANGES.md
- bower.json
- package.json
> release: 3.1.0

- CHANGES.md
- spec/wavesurfer.spec.js
- src/wavesurfer.js
> throw error when url parameter is not supplied to load()

- CHANGES.md
- package.json
> specify non-minified wavesurfer.js in main entry of package.json

- CHANGES.md
- spec/mediaelement.spec.js
- src/mediaelement.js
- src/wavesurfer.js
follow-up to #1774 
fixes #1773
> throw error when invalid url is passed to MediaElement backend

- faq/index.html
> scale-json.py: limit nr of digits to 2

- src/drawer.js
This is in line with how the single click event handler does it.
#1765
Thanks to @thijstriemstra for pointing me in the right direction :)
> Expose progress to the dblclick event

- docs/methods.html
> docs: remove non-existing method

- src/drawer.multicanvas.js
- src/wavesurfer.js
I too wanted to scrub out the gaps in my bar waveform.  I'd add html documentation but I'm really not sure how that stuff works.
fixes #1693
> add barMinHeight option

- docs/methods.html
parsed to the -> passed to the
> methods.html: typo fix

- src/plugin/regions.js
1. Yoda conditions aren't normally used in this codebase.
2. The drag events caused `bindEvents` to be very long, and lead to very indented code, so I put them in their own function.
> regions plugin: refactors

- src/plugin/regions.js
There was issue of region's handle positioning in render. Handle style was previously changed due to channelIdx feature implementation. Region handle styles (top, height) where changed to original values.
> regions plugin: handle position fix while using with channelIdx param

- CHANGES.md
- bower.json
- package.json
> release v3.3.1

- src/plugin/spectrogram.js
correct the hamming windfunc formula
fixes #1850
> spectrogram plugin: correct the hamming windfunc formula

- CHANGES.md
> Minor typos fixes

- faq/index.html
Skip the intermediate .dat file.
Update the FAQ documentation - remove the "generate dat" step.
n/a
n/a
n/a
n/a
> Remove one step in the data generation workflow.

- README.md
> Add npm package name to readme

- example/timeline/index.html
> doc: update timeline plugin example documentation

- CHANGES.md
- src/wavesurfer.js
> change default desynchronized drawing context attribute to false

- CHANGES.md
- bower.json
- package.json
> bump version: v3.3.3

- example/spectrogram/index.html
> docs: fix error

- example/microphone/index.html
- src/plugin/microphone.js
**Title:**  Documentation Type change in Microphone Plugin
Changing documentation LocalMediaStream to MediaStream
As documented here: https://developer.mozilla.org/en-US/docs/Web/API/LocalMediaStream
> microphone plugin: change LocalMediaStream to MediaStream in docs

- package.json
- src/mediaelement.js
- src/wavesurfer.js
this was breaking CI builds.  unclear how/why it wasn't breaking locally.
> remove no-eslintrc flag

- example/regions/app.js
- example/regions/index.html
this PR includes #1970, I will merge them separately tho.  Adds some nice buttons to the regions plugin example and gives us a way to test looping / region playback.
> Improve region example

- CHANGES.md
- bower.json
- package.json
> release 4.0.1

- CHANGES.md
- karma.conf.js
- spec/drawer.spec.js
- spec/util.spec.js
- src/drawer.js
- src/util/clamp.js
- src/util/index.js
seekTo fix for issue #1816, with basic unitTests
fixes #1816
> seekTo bugfix inc. basic unit tests

- CHANGES.md
- README.md
- bower.json
- package.json
@katspaugh can you merge/tag/publish this?
> release 4.1.0

- CHANGES.md
- bower.json
- package.json
> release: 4.1.1

- CHANGES.md
- bower.json
- package.json
> release: 4.2.0

- projects/index.html
> projects: include link to Music Speed Changer

- CHANGES.md
- example/bars/index.html
- example/bars/main.js
- src/drawer.multicanvas.js
Added ability to draw multi channel bars with different colors similar to regular line wave
None
None
refs #1722
> Update to support multi channel colors for bars

- CHANGES.md
- LICENSE
- package.json
> release: 4.4.0

- example/playlist/sample.m3u
> examples: add missing sample.m3u

- projects/index.html
> Added MediaEdits.io to Commercial List

- CHANGES.md
- src/plugin/microphone/index.js
> microphone plugin: remove deprecated MediaStream.stop call

- CHANGES.md
- bower.json
- package.json
can you merge/tag/release this manually @katspaugh?
hopefully last time (#2191) 😄
> release: 4.6.0

- .github/workflows/publish.yml
- .github/workflows/test.yml
- README.md
Verifying the workflow syntax.
> Testing the actions

- .eslintrc.js
- example/stretcher/soundtouch.js
- spec/drawer.spec.js
- src/drawer.multicanvas.js
- src/plugin/cursor/index.js
- src/plugin/markers/index.js
- src/plugin/playhead/index.js
- src/plugin/regions/index.js
Introduce consistency for if statements.
> eslint: enable curly rule

- .github/workflows/publish.yml
- CHANGES.md
- bower.json
- package.json
- src/plugin/playhead/index.js
- src/util/orientation.js
> release: 5.0.0

- CHANGES.md
- spec/drawer.spec.js
- src/drawer.js
> fix removing DOM element in destroy()

- CHANGES.md
- example/markers/app.js
- src/plugin/markers/index.js
Markers can now be provided with an image to display instead of the default pointer image when being added.
> markers plugin: added support for custom marker elements

- _config.yml
- plugins/index.html
- plugins/markers.html
- plugins/markers.js
**Title:** Markers plugin: [gh-pages] add markers plugin doc page
https://github.com/katspaugh/wavesurfer.js/pull/2287 (markers plugin: trigger click event on wavesurfer )
> Markers plugin: [gh-pages] add markers plugin doc page

- src/plugin/regions/region.js
> regions plugin: fix Intervention message on mobile devices

- example/timeline-notches/index.html
> examples: fix sample code in timeline-notches

- example/minimap-vertical/index.html
- example/minimap-vertical/main.js
- src/plugin/cursor/index.js
- src/plugin/minimap/index.js
Use oriented event and DOM targets in cursor and minimap plugins, so that they work properly in vertical mode
no
no
> plugins: support vertical mode in cursor and minimap plugins

- docs/options.html
to be merged after the following pr:
#2367
> add hidecursor to docs

- CHANGES.md
- src/mediaelement.js
> workaround for seekTo occasionally crashing on Firefox

- README.md
I've created an NFT on Polygon that represents the initial commit to this repo.
I think it would be a nice way to support the project and celebrate the 10 years.
WDYT, @thijstriemstra?
> Readme: add info about a 10-year NFT

- CHANGES.md
- spec/wavesurfer.spec.js
- src/drawer.canvasentry.js
> Restore support for passing CanvasGradient to setWaveColor()

- CHANGES.md
- src/wavesurfer.js
> Fixes potential error with clientWidth on resizing

- README.md
Looks like there's very little interest in this (only 190 views on OpenSea), plus there's a typo in the image (#2500).
> Chore: remove nft from the readme

- src/plugin/markers/index.js
**Title:** Add tooltip for marker plugin.
Closes #2589
CC: @simoneb
> feat(markers): add tooltip

- README.md
GitPOAP is an NFT for contributors. Our project is here: https://www.gitpoap.io/gh/katspaugh/wavesurfer.js
Basically, each merged PR earns you a POAP and a GitHub bot will post a corresponding comment in the PR.
> Add a GitPOAP badge in the readme

- CHANGES.md
- src/plugin/markers/index.js
Fixing of issue, added listeners check after add
N/A
N/A
Not fully tested
fixes #2560
> markers plugin: check for event after every add/remove

- docs/methods.html
This added doc is helpful for users to know how to redraw a wave on canvas responsively
> Add drawBuffer method in the documentation

- README.md
To make it easier to start using the package.
> Docs: add an import snippet

- CHANGES.md
- bower.json
- package.json
6.5.0
------------------
- Regions plugin:
- Improved delta calculation (resize end) (#2641)
- Fix iphone silent switch webaudio mute (#2667)
- Respect mute state when changing volume during mute (#2502)
> release: 6.5.0

- CHANGES.md
- bower.json
- package.json
6.6.0 (12.03.2023)
------------------
- [Regions] Fix undefined content element on remove (#2713)
- Zoom optimisation for Waves and matching implementation for Spectrograms (#2646)
- Fix: release workflow permissions (#2709)
> Release 6.6.0

- projects/index.html
Request to add EasySub to the project listing page
> submit EasySub

- .github/workflows/publish.yml
- package.json
Resolves #2723.
I've fixed it by adding npm install. Tested by triggering the action on this branch and publishing with `--dry-run`. ✅
> Fix: NPM publish in the CI job

- src/webaudio.js
Resolves #1281. Removes the deprecated [ScriptProcessorNode](https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode).
The only purpose of this node in our code was to track time in the WebAudio backend. It's now being done via `requestAnimationFrame` instead. It's a little less precise, but much lighter on the CPU and good enough for rendering.
There are no breaking API changes. It's still possible to pass and external scriptNode in the options, but it won't be used for timing. It will be just added to the graph like before.
We should eventually deprecate the option, too.
> Refactor: remove deprecated ScriptProcessorNode

- CHANGES.md
- bower.json
- package.json
6.6.3 (04.04.2023)
------------------
- Markers plugin:
- allow removing markers by passing a marker object (#2749)
- add getMarkers function (#2743)
- Docs: version the unpkg script in readme (#2746)
- Refactor: remove scriptNode (#2706)
> Release 6.6.3

- README.md
Encourage people to try out the alpha version. I'd like to gauge how compatible it is with the existing applications and whether it's missing some features folks need.
> Docs: add a note about wavesurfer.ts

- package.json
As per this discussion: https://github.com/katspaugh/wavesurfer.js/discussions/2813
> Package: export all js files in dist

- cypress/e2e/regions.cy.js
- examples/envelope.js
- src/draggable.ts
- src/plugins/envelope.ts
- src/plugins/regions.ts
- src/renderer.ts
- src/wavesurfer.ts
The same code was used in three different places, so I extracted it into a module.
> Refactor: extract makeDraggable

- .github/workflows/release.yml
- package.json
The old action was not maintained.
> Chore: update the release action

- src/renderer.ts
- src/wavesurfer.ts
Resolves [#2810](https://github.com/katspaugh/wavesurfer.js/discussions/2810#discussion-5251147)
`barAlign` will vertically align bars.
requires e2e tests
> Feat: add vertical bar alignment

- src/renderer.ts
> Fix: rm desynchronized: true

- .github/workflows/lint.yml
- package.json
- src/renderer.ts
- src/wavesurfer.ts
Use a marketplace-verified GH Action instead of an old one.
See https://github.com/marketplace/actions/eslint-plus
> Chore: fix eslint action

- README.md
> Readme: fix links

- .github/workflows/ai-review.yml
Experimental: OpenAI-based PR reviewer.
See https://github.com/marketplace/actions/openai-chatgpt-based-pr-reviewer-summarizer
Release Notes:
- New Feature: Added GitHub Action workflow "AI code review" that triggers on pull requests and pull request review comments. Uses external action "fluxninja/openai-pr-reviewer" for AI-based code reviews. Configured environment variables and options.
- New Feature: Added step to "AI code review" workflow to check out repository code and install dependencies using npm.
- Bug fix: Updated "AI code review" workflow to run the code review action only on pull requests targeting the main branch.
> "Code reviewed with AI's might,
> Pull requests shine in the light.
> Bugs are fixed, features are born,
> With each commit, we're reborn."
> Chore: GitHub action to review PRs with AI

- src/plugins/hover.ts
Resolves #3023
Using clientX and bbox instead of offsetX fixes the issue.
> Fix: [Hover] hovering over regions

- src/wavesurfer.ts
Resolves #3103 and #3104.
The interaction even now calculates the new time at the position of the interaction instead of passing the current time.
I've also removed the duration cache to make it more robust (albeit slower).
> Fix: pass new time to the interaction event

- src/decoder.ts
- src/wavesurfer.ts
> fix: unawaited promises fixes #3126

- examples/envelope.js
- src/plugins/envelope.ts
iOS doesn't let you control a media element's volume programmatically. The only option is to use Web Audio.
> Fix: [Envelope] volume on iOS via WebAudio gain

- README.md
- examples/envelope.js
- src/plugins/envelope.ts
* A long press on touch devices will add a point.
* Removed deprecated methods (will be released as 7.3.0).
> Feat: [Envelope] long touch to add a point

- package.json
- src/plugins/envelope.ts
Envelope feature: allow passing an AudioContext so that multiple audio tracks can be played in the same context.
> Feat: [Envelope] allow passing an audio context

- README.md
- examples/styling.js
- src/renderer.ts
Resolves #3175
Just add a part so that the wrapper element can be styled.
Try to add a CSS style from your "host" application and see it change.
> Add part to the wrapper element

- .gitignore
- cypress/e2e/options.cy.js
- package.json
- src/wavesurfer.ts
- tsconfig.json
- yarn.lock
Resolves #3282
If both `peaks` and `duration` are passed in the options, a waveform will be rendered w/o audio. An audio file can be later loaded with `load(url, peaks, duration)`.
> Feat: render pre-decoded waveform w/o audio

- src/plugins/minimap.ts
Resolves #
Pass peaks of every channels to minimap
```javascript
const ws = WaveSurfer.create({
container: document.body,
duration: 5675,
url:'/file.mp3',
splitChannels: [
{
waveColor: 'rgb(200, 0, 200)',
progressColor: 'rgb(100, 0, 100)',
},
{
waveColor: 'rgb(0, 200, 200)',
progressColor: 'rgb(0, 100, 100)',
},
],
minPxPerSec: 1,
hideScrollbar: true,
autoCenter: false,
dragToSeek: true,
plugins: [
// Register the plugin
WaveSurfer.Minimap.create({
splitChannels: [
{
waveColor: 'rgb(255, 0, 200)',
progressColor: 'rgb(100, 0, 100)',
},
{
waveColor: 'rgb(0, 255, 200)',
progressColor: 'rgb(0, 100, 100)',
},
],
height: 30,
dragToSeek: true
})
]
});
ws.on('interaction', () => {
ws.play()
});
```
> Handling multi channel peaks

- src/plugins/regions.ts
> fix: [Regions] remove regions container on destroy

- cypress/e2e/basic.cy.js
- src/fetcher.ts
- yarn.lock
Fetch errors weren't propagated properly.
> Fix: catch 400/500 errors

- src/plugins/hover.ts
Resolves #3348
The mouse position indicator now re-renders when zooming using the mouse wheel.
> Fix: [Hover] update on mousewheel

- package.json
- rollup.config.js
- yarn.lock
Resolves #3446
rollup-plugin-dts causes duplicate types exported from the package.
> Fix: revert rollup-dts

- .github/workflows/release.yml
- package.json
- rollup.config.js
- src/wavesurfer.ts
Add an init event that is emitted after a wavesurfer instance is created.
> Feat: add init event

- src/fetcher.ts
Resolves [Bug preventing blob waveform rendering on iOS](https://github.com/katspaugh/wavesurfer.js/discussions/3466)
> Fix: fetcher error catching improvement

- .github/workflows/release.yml
In the release changelog, add the username of the PR auther next to it.
> Chore: add contributor usernames to changelogs

- src/webaudio.ts
Resolves #3517
The Web Audio player wasn't handlng time correctly with a non-default playback rate.
> Fix: playback rate with Web Audio

- package.json
> Version bump to 7.7.3

- package.json
> Version bump to 7.7.5

- .github/workflows/lint.yml
- cypress/e2e/basic.cy.js
- package.json
New lint action: https://github.com/marketplace/actions/eslint-annotate-from-report-json
The old action has been failing recently.
> Chore: update code linting action

- package.json
- yarn.lock
Just a routine depenendencies update.
> Chore: update dev dependencies

- examples/timeline-custom.js
Updates `timeline-custom.js` to remove typos.
NA
NA
NA
* [NA] This PR is covered by e2e tests
> Nit: Update `timeline-custom.js` Example

- package.json
> Chore: update dist exports

- src/plugins/regions.ts
Resolves #3842
Add a flag for whether a region is removed or not. When a region DOM element is created asynchronously (due to virtualization) but the region is already removed, don't create the element.
> Fix(Regions): fix async region removal

- examples/timeline-custom.js
Fixes link in examples.
The wrong links is also the case for other example pages, let me know if you want to fix them all. (that's why draft pr)
> Updates link to timeline plugin

- AI_OVERVIEW.md
This small PR fixes the agents guide reference in `AI_OVERVIEW.md`.
> Update agents guide reference

- src/plugins/hover.ts
Resolves #4141
Make sure hoverPlugin does NOT listen to wheelEvent, but instead listens for wavesurfer's zoom & scroll events, so that we update the hover position only AFTER the zoom and scroll happens.
Instantiating wavesurfer with code below, and try hovering while zooming/scrolling (using mouse wheel).
```
/**
* Zoom plugin
*
* Zoom in or out on the waveform when scrolling the mouse wheel
*/
import WaveSurfer from 'wavesurfer.js'
import ZoomPlugin from 'wavesurfer.js/dist/plugins/zoom.esm.js'
import Hover from 'wavesurfer.js/dist/plugins/hover.esm.js'
// Create an instance of WaveSurfer
const wavesurfer = WaveSurfer.create({
container: '#waveform',
waveColor: 'rgb(200, 0, 200)',
progressColor: 'rgb(100, 0, 100)',
url: '/examples/audio/audio.wav',
minPxPerSec: 100,
plugins: [ …
```
> fix(Hover plugin): listen to zoom/hover instead of wheel
