- src/mediaelement.js
- src/wavesurfer.js
I added support for video elements. The code is a bit messy with the double dependencies but I can't think of a better way to solve this easily. I made a [repo with an example code](https://github.com/RocAlayo/example-video-wavesurfer.js) and a [test website](http://development.example-video-wavesurfer.divshot.io).
> Adds support for using video element

- example/annotation/index.html
Can't find Bootstrap without the `http:` when opened in local HD.
> locally viewed fix

- plugin/wavesurfer.regions.js
With this changes now the start and end of the region won't oversize the wave element in any case.
> Region now won't oversize the wave element

- example/equalizer/main.js
Fix for #395. After submitting the issue, realised what the problem was. Filter type was not being mapped and set correctly from the EQ array, so was just defaulting to 'lowpass'.
I'll be honest - I'm not sure why the capitalisation of the filter type stopped it working, but it did. If you're any wiser than me on that, I'd love to find out!
Tested on Chrome 40.0.2214 and Firefox Developer Edition 38.0a2
> Fixing equalizer example

- plugin/wavesurfer.microphone.js
- src/drawer.js
Sometimes right after destroying a wavesurfer, an additional `drawer.style` call is made somewhere but since the element does not exist, it throws an error in `drawer.js`:
```
TypeError: el is null
if (el.style[prop] != styles[prop]) {
```
This PR makes sure the element exists before styling it.
> make sure the element exists before styling it

- plugin/wavesurfer.regions.js
With this code i easier  to use the dragging and resizing of region because if the mouseup event happens outside the wavesurfer element this actions are stopped and you don't get stuck with it until you click again. This way is easier to adjust a region to the star or end of the wave.
> Added listener on mouseup to body for region usability improvement.

- src/webaudio.js
This fixes the bug in #400. Direct path from analyser to gain node is
disconnected before connecting filters in turn, so that all audio goes
exclusively through the inserted filters now.
> Fix for #400: disconnect direct path in 'FX loop'

- README.md
I noticed when testing fallback that setting AudioElement doesn't seem to do anything, but MediaElement does.
> Updating readme description for backend parameter

- package.json
…n js file
I'm not sure of the backstory here, but it looks like there has been some conversation around bower in the past. 
I'm noticing that when trying to use wiredep in grunt to automatically pull in bower_components, it fails for wavesurfer.js because main is not correctly set in package.json . 
Can we change main to what's proposed in the PR? Or if not, create a bower.json file that defines main as the .js in the dist folder? 
Currently have to use this workaround in our bower.json file for wiredep to work:
```
"overrides": {
"wavesurfer.js": {
"main": "dist/wavesurfer.min.js"
}
```
> package.json js location causing bower/wiredep issues

- src/drawer.canvas.js
- src/webaudio.js
This allows waveforms to be asymmetric around zero, and to see the actual wave shape when you are zoomed in far enough (or if the wave shape has low enough frequency). 
See the comparison screenshot of a zoomed-in rumble.  Top is current code, bottom is with this patch.  
This resolves https://github.com/katspaugh/wavesurfer.js/issues/449 .
> Canvas waveforms show true min and max peaks

- README.md
I noticed that **Mouse Events** wasn't formatted correctly under **Region Events**. I also added a link to the browser support for Web Audio to http://caniuse.com/audio-api
> Updating README formatting and resource links

- README.md
- example/angular/index.html
- example/annotation/index.html
- example/audio-element/index.html
- example/elan/index.html
- example/equalizer/index.html
- example/microphone/index.html
- example/panner/index.html
- example/playlist/index.html
- example/spectrogram/index.html
- example/split-channels/index.html
- example/timeline/index.html
- example/zoom/index.html
- index.html
All examples now also work on https (http://katspaugh.github.io/wavesurfer.js/ for example).
> use protocol relative urls for https in examples and documentation

- README.md
- plugin/wavesurfer.regions.js
- src/wavesurfer.js
I noticed that on zooming the regions do not redraw themselves, which results in them being displayed incorrectly. 
* Make the region call updateRender on zoom so its
rendering matches the wavesurfer's scale
* update readme
> Add zoom event

- README.md
- src/drawer.js
- src/wavesurfer.js
This seems like a common use case. At least for the thing I'm building, it's pretty distracting to have the waveform move while playing, as I'm often zoomed in really far, so it would be nice to disable it.
The default behavior is the same as the old behavior. 
Thanks for the great library btw
> Add autoCenter option

- src/mediaelement.js
Enable autoplay for backend "mediaelement". Background is the `canplay` event on an `<audio>` element, which is mapped to `ready` in wavesurfer is not triggered automatically on iOS. The [workaround](http://stackoverflow.com/questions/9920297/html5-audio-canplay-event-doesnt-fire-on-safari-mac-desktop) is to set `autoplay` to `true` and pause the audio as soon as the `ready` event is fired.
Note: This could provide a workaround for #429.
```javascript
wavesurfer.init({autoplay: true});
wavesurfer.on('ready', function() { wavesurfer.pause(); })
```
> Configure autoplay for mediaelment

- example/annotation/app.js
- example/audio-element/main.js
- example/zoom/main.js
There were a few cases where AudioElement was still being used in the example code.
> Replace depreciated AudioElement with MediaElement in examples

- plugin/wavesurfer.microphone.js
Safari and IE still doesn't support it. This will avoid the undefined reference error.
> check does browser support getUserMedia

- example/annotation/app.js
For proper silence detection, we should actually be taking the absolute value of the peaks. `<=` allows us to use true silence (0.0) as our detection threshold. Also, it would be better to measure RMS instead of peak values. I may add a getRMS function later.
Thanks!
> use absolute value for peaks

- src/wavesurfer.js
As mentioned in #498, #592, and #611 
I smoothed out the movement of the play bar while using a MediaElement backend by polling for updates using requestAnimationFrame.  The update loop is broken on pause and ended.
You can see the improvement by comparing:
http://rawgit.com/jj227/wavesurfer.js/master/example/annotation/index.html
http://rawgit.com/katspaugh/wavesurfer.js/master/example/annotation/index.html
> Smoothed out the movement play bar while using a MediaElement backend

- src/wavesurfer.js
IE 9/10 does not support window.devicePixelRatio.  Wavesurfer.js doesn't seem to officially support IE 9/10, but a number of members of the community are interested in supporting IE 9/10.  Our project is using wavesurfer and is supporting IE 9/10 by generating PCM on server side, and using MediaElement fallback.
> Polyfill for IE 9/10 for window.devicePixelRatio

- plugin/wavesurfer.spectrogram.js
ScriptProcessor is created with parameter 'bufferSize' set to 0, it'll select a default value (4096) which is too big for short audio recording. Hence the spectrogram is rendered with very wide pixel blocks. This commit will determine the best buffer size depending on the length of the recording and the width of the canvas.
After the fix:
> Fix ScriptProcessor's buffer size

- Gruntfile.js
- package.json
We're having trouble with the build creating extra files when there are already files in `dist`, so here's a `clean` task for deleting `dist` before each build to keep that from happening. #608
> Add clean to build

- src/webaudio.js
The getPeaks function was using the first sample in each channel to initialize the min and max values, causing files that start above or below zero to be drawn with persistent offsets. Initializing the min and max to 0 fixes this.
> Change getPeaks baseline to zero

- spec/util.spec.js
- src/drawer.js
- src/drawer.multicanvas.js
- src/util.js
I need very large canvases for some personal light sequencing software I'm working on (for an interactive xmas light display), and I quickly hit Chrome's canvas address limitations, as detailed in the following issues:
- #47
- #413
I have implemented a Drawer that uses multiple adjacent canvases, and draws seamlessly between them. I've attached a zip file containing the following examples:
- A 50000px waveform
- Multiple canvases with bars
- Multiple canvases with split channels
- A waveform with pixel ratio of 10
- Lots of tiny canvases
To see the examples, run multicanvas-tests/src/app-test.html.
I'm no JavaScript expert, so it's possible I'm not always following best practices. I figure there are a few options for this drawer:
1. Replace the current CanvasDrawer with this one (rename …
> Multi-Canvas Renderer

- src/drawer.js
> Fix click-to-seek for audios which are not spanning the entire canvas

- src/drawer.multicanvas.js
Implemented fix proposed by @chinshr, with a minor change. I calculate the `length` variable in the `drawWave` method instead of `drawLine` to avoid redundant calculations.
Please don't accept until @chinshr has had a look.
> Change MultiCanvas line drawing logic to handle prerendered peaks

- src/drawer.multicanvas.js
Renamed `clearWave()` to `clearWaveForEntry()`. Added `clearWave()` method that calls `clearWaveForEntry()` on all canvases.
Question: The only thing calling `clearWave()` is the `setChannel()` method in `wavesurfer.js`. This method isn't in the API documentation as far as I can tell. Is it still used?
> Remove argument from MultiCanvas clearWave() method

- plugin/wavesurfer.regions.js
This will fix a bug where out/region-out events are fired once the in/region-in processes.
> Flip the in/out regions processing conditionals

- src/mediaelement.js
WaveSurfer.MediaElement#getDuration throwed `TypeError: Not enough
arguments` in Safari 9.1. It also violated contract specified in [HTML Time ranges](https://developers.whatwg.org/the-video-element.html#dom-timeranges-end).
This should fix #719.
> MediaElement#getDuration throwing TypeError fixed

- src/drawer.canvas.js
- src/wavesurfer.js
- src/webaudio.js
Temporarily revert #689 due to a regression described in #724.
@whenov we'll restore this feature after we come up with a solution to transparently insert new nodes into the Web Audio graph keeping the graph further extensible.
> Revert "Allow to play/draw one channel specified by parameter"

- plugin/wavesurfer.regions.js
I noticed when clicking around to move the cursor, it was too easy to accidentally create a region. This addresses that issue. Default value is 2 pixels, and it can be overridden as well:
```javascript
wavesurfer.enableDragSelection({ slop: 0 });
```
> Added option for slop protection

- plugin/wavesurfer.timeline.js
A merge request to cover #696. I have endeavoured to maintain backwards compatibility with the `Canvas` renderer. I have attached a [multicanvas-timeline-tests.zip](https://github.com/katspaugh/wavesurfer.js/files/349198/multicanvas-timeline-tests.zip) file containing my changes, along with a test html and js file in the `src` directory that can be run to visually observe the results.
I don't personally use the timeline plugin, so there may be some edge cases that I'm not aware of. I've changed some function names, e.g. `drawTimeCanvas` -> `drawTimeCanvases`, so that's a potential breaking change.
@chinshr and @jeremylach, it would be great if you could download the attached zip file and see if the changes meet your needs before the changes are merged (assuming they are ☺).
> Enhance timeline plugin to support multi-canvas rendering

- plugin/wavesurfer.regions.js
With regards to issue #717 I was looking into it as it was something I wanted to change too so I just went ahead with it. Hopefully that's alright.
Overall, I feel it's much more intuitive now as regions don't magically resize. This is especially true when you set resizing to false but end up dragging the region to the side as well.
> adding controls to ensure region size does not change and sliding stops when the sides are reached

- projects/index.html
Add project request from #728.
Project does indeed use wavesurfer, and the page comes up clean when scanned with VirusTotal.
> Add CutMp3 Online to Projects list

- src/drawer.multicanvas.js
My fix for #790 means that we get an extra redraw upon initial load. This is fine, but it woke up a sleeping bug. The initial redraw throws the following exception in Chrome:
```Uncaught TypeError: Cannot read property 'waveCtx' of undefined```
I forgot to delete a bit of code from my initial implementation of MultiCanvas. It was naively setting the fill styles of the first canvas element in the array, even if the array is empty.
I already have the proper code in place for this (`fillRect()` calls `setFillStyle()`), so the fix is to simply delete the bit of old code.
> Fix MultiCanvas bar drawing exception

- src/wavesurfer.js
Zoom should not modify the play position. Removing seek greatly increases performance while zooming.
> Only recent on zoom, removed seek

- dist/wavesurfer.js
Bug possibly caused by: https://github.com/katspaugh/wavesurfer.js/pull/803
By not seeking, the play percentage is not updated. Instead, we call it directly to avoid seekTo overhead.
> Fix Play Percentage on Zoom when audio paused.

- src/drawer.multicanvas.js
> 814: Pre-generated waveform on MultiCanvas and zoom doesn't fill out each canvas

- .gitignore
- src/wavesurfer.js
Also, had to manually copy changes that had been merged into upstream/master dist files only into the src files... otherwise my change would overwrite those changes... That goes for a fix from https://github.com/katspaugh/wavesurfer.js/pull/806 and the scale calculation in src/drawer.multicanvas.js.
> Fixed: JS crash occurs after audio data has been decoded, if the WaveSurfer instance has been destroyed in the meantime

- src/mediaelement.js
Added a way to define the the preload attribute of the HTML5 audio markup.
'Metadata' and 'None' saves bandwidth, especially if there is multiple players on the page.
'Metadata' allows to have track length.
Default is left to 'auto' to avoid unexpected change for wavesurfer users.
Note that this attribute interpretation may be different on different browsers.
> Added HTML Variable Preload Attribute

- plugin/wavesurfer.regions.js
In Firefox, using the scrollbars (with the mouse pointer) would trigger a region selection. The fix for this might be a bit hacky, but it works.
Tested in Mac Chrome, Firefox, Safari, and Windows Chrome, Firefox.
Fixes #830, fixes #748, fixes #843
> Fixed a bug in Firefox and scrollbar usage

- src/webaudio.js
There is a maximum amount (6) for active audioContexts, so this allows on the fly enabling/disabling without reaching that limit (if the number of currently active acs is always below 6)
https://developer.mozilla.org/en/docs/Web/API/AudioContext/close
> close the audiocontext in the destroy method of the webaudio backend

- projects/index.html
Hey I finally setup a git hub project site for our project...  It would be great if you could link to that in you projects using.
I've used jekyll like once before and I think it's cool to edit those files directly?
> change electro link to our new project site

- src/mediaelement.js
When running code that uses Wavesurfer under PhantomJS (even if not explicitly testing the Wavesurfer code), the JS interpreter crashes because PhantomJS DOM `<audio>` elements don't have a `load()` method. This change skips that one line if the method doesn't exist.
> Only call media.load() if it exists

- src/drawer.canvas.js
- src/drawer.multicanvas.js
> Apply correct normalize absmax calculation to drawBars()

- src/drawer.canvas.js
- src/drawer.js
- src/drawer.multicanvas.js
I noticed the calculation from progress to pos in updateProgress was already done in drawer's progress function, which I believe is the only place where updateProgress is called.
> small refactor, removed unnecessary re-calculation

- Gruntfile.js
- karma.conf.js
- spec/peakcache.spec.js
- src/drawer.canvas.js
- src/drawer.js
- src/drawer.multicanvas.js
- src/mediaelement.js
- src/peakcache.js
- src/wavesurfer.js
- src/webaudio.js
* Adds an optional 'partialRender' parameter to enable
* Calculates and renders peaks only for current visible waveform
* Keeps track of currently calculated/rendered peaks to avoid
duplicate calculation and only incremental scroll changes are rendered
Tested all combinations of Canvas/MultiCanvas and Wave/Bars rendering
at various zoom levels.
> Improve rendering performance when pxPerSec is high

- src/wavesurfer.js
while audio is playing, i seek to backward. the cursor is still in its original position. until playing to the original position. the cursor is return to normal.
> fix draw wrong position while playing backward seeking

- .eslintrc.js
- .travis.yml
- example/timeline/index.html
- package.json
- src/plugin/timeline.js
- src/webaudio.js
* Timeline parameters are constructed in an object literal
* variables are locally scoped where possible to reduce build size when minifying
* plugin options now extend defaults in an object literal and are cached in `this.params`.
* Intervals for the timeline labels (`timeInterval`, `primaryLabelInterval`, `secondaryLabelInterval`) can now be defined as raw values (as before) – or as a callback which receive `pxPerSec` as parameter and return the interval. – The calculated defaults are the same as before.
* Improved plugin life cycle management, things get destroyed, unhooked etc.
* Smaller minified builds
* Make plugin work better with the (dynamic) plugin API
* Make code more readable
/
/
https://github.com/katspaugh/wavesurfer.js/pull/893/commits/db392aa847f9f5b80f0e098180f0b8c71641e87 …
> Next: Refactor timeline plugin

- .travis.yml
- karma.conf.js
- package.json
- spec/peakcache.spec.js
- src/drawer.canvas.js
- src/drawer.js
- src/drawer.multicanvas.js
- src/mediaelement.js
- src/peakcache.js
- src/wavesurfer.js
- src/webaudio.js
* Adds an optional 'partialRender' parameter to enable
* Calculates and renders peaks only for current visible waveform
* Keeps track of currently calculated/rendered peaks to avoid
duplicate calculation and only incremental scroll changes are rendered
Tested all combinations of Canvas/MultiCanvas and Wave/Bars rendering
at various zoom levels.
> Next: Merge from master: Improve rendering performance when pxPerSec is high (#909)

- src/drawer.canvas.js
- src/drawer.multicanvas.js
fixes broken split channel rendering caused by out-of-date call to drawWave + drawBars without the start and end parameters introduced by peakCache
> Fixes broken splitChannel rendering (issue #942)

- src/mediaelement.js
Change getDuration function in mediaelement.js to return the correct duration length same as WebAudio.
from
var duration = this.media.duration; // incorrect duration value returned
console.log preview:
to
var duration = this.buffer.duration; // correct duration value returned same as WebAudio
console.log preview:
> fix getDuration() return value when using MediaElement

- plugin/wavesurfer.minimap.js
Updated the render function to call the new version of the getPeaks and drawPeaks calls which now require start and end parameters.  Fixes flat waveform drawing in minimap plugin.
> Updated render function for drawPeaks/getPeaks

- plugin/wavesurfer.timeline.js
I'm integrating wavesurfer.js into an Ember project and have found that in this context canvas enumeration in the timeline plugin is incorrectly iterating over array properties.
> avoid 'for in' array enumeration

- src/webaudio.js
add check for browser support of AudioContext.close(). This is only supported by Chrome 43+ and FireFox 40+ for now. Edge and other non supported browsers will give an undefined error. #949 
https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/close
// check if browser supports AudioContext.close()
if(typeof this.ac.close() !== 'undefined'){
this.ac.close();
}
> check if browser supports AudioContext.close in webaudio.js

- src/drawer.multicanvas.js
- src/mediaelement.js
- src/plugin/minimap.js
- src/plugin/timeline.js
- src/wavesurfer.js
- src/webaudio.js
* Fixes the bugs that came up because of out-of-date calls to `getPeaks` and `drawPeaks` (minimap plugin and when rendering split channels) (on master https://github.com/katspaugh/wavesurfer.js/pull/945 and https://github.com/katspaugh/wavesurfer.js/pull/959)
* Fixes the incorrect `for ... in this.canvases` loops in timeline plugin and multicanvas renderer, refactored to use `forEach` where possible (on master https://github.com/katspaugh/wavesurfer.js/pull/961)
* Turn unnecessary `let` into `const`
* Fixes "only half the waveform is being drawn" bug
* Includes ports of a few minor changes added to master for the next branch
* Only the uncontroversial part of https://github.com/katspaugh/wavesurfer.js/pull/963
/
/
/
> Next: Minor bugfixes and ports of changes from master

- src/util.js
Can be used with a resize event to prevent drawBuffer() from running concurrently when resizing the browser window. @mspae @thijstriemstra #963 
**preview:**
http://codepen.io/entonbiba/pen/jyKrEz
var responsiveWave = WaveSurfer.util.debounce(function() {
wavesurfer.empty();
wavesurfer.drawBuffer();
}, 150);
window.addEventListener(‘resize’, responsiveWave);
> create debounce method in util.js

- docs/events.html
There was no documentation for the waveform-ready event.
> Documentation for the waveform-ready event.

- docs/methods.html
There were 2 missing parameters for .load() in the documentation: peaks and preload.
I also removed the line "Returns XHR object" as this is not the case.
This is potentially blocked by #973
> Adding missing parameters to .load()

- src/wavesurfer.js
This prevents a `Failed to execute 'stop' on 'AudioBufferSourceNode'` when stop() is called before play().
> avoid error when calling pause before play

- src/wavesurfer.js
Returns the current gainNode volume.
You can now do wavesurfer.getVolume() to return the current playback volume.
> getVolume method

- src/wavesurfer.js
The method will return an array of all the set filters.
For example when doing something like this:
````
// setFilters
var lowpass = wavesurfer.backend.ac.createBiquadFilter();
wavesurfer.backend.setFilter(lowpass);
// getFilters
wavesurfer.getFilters();
````
> add getFilters method

- .esdoc.json
- .travis.yml
- README.md
- package.json
- src/util/style.js
- src/wavesurfer.js
* Adds [esdoc](https://esdoc.org/) – It compiles and analyses all the jsdoc comments and builds a HTML representation into a `doc` directory. (`npm run doc`)
* Other minor changes
* Added doc generation to `.travis.yml`
* updated some jsdoc comments that produced errors
* documentation :birthday: 
/
/
* documentation coverage is currently at 24.06% …
> Next: Esdoc build script

- .gitignore
- .npmignore
The current (1.3.2) npm package contains a lot of unnecessary files for an NPM user:
```
$ ls -l node_modules/wavesurfer.js/
total 60
-rw-rw-r--  1 thijs thijs  343 feb  7 12:19 bower.json
-rw-rw-r--  1 thijs thijs 1923 feb  7 12:23 CHANGES.md
-rw-rw-r--  1 thijs thijs   18 feb 14  2016 CNAME
drwxrwxr-x  4 thijs thijs 4096 feb  8 22:38 coverage
drwxrwxr-x  3 thijs thijs 4096 feb  8 22:38 dist
drwxrwxr-x 20 thijs thijs 4096 feb  8 22:38 example
-rw-rw-r--  1 thijs thijs 5481 jan 19 16:43 Gruntfile.js
-rw-rw-r--  1 thijs thijs 1302 jan 19 16:43 karma.conf.js
-rw-rw-r--  1 thijs thijs 2801 feb  8 22:38 package.json
drwxrwxr-x  2 thijs thijs 4096 feb  8 22:38 plugin
-rw-rw-r--  1 thijs thijs 4411 jan 19 16:43 README.md
drwxrwxr-x  3 thijs thijs 4096 feb  8 22:38 spec
drwxrwxr-x  2 thijs thijs …
```
> Cleanup npm package

- src/webaudio.js
Fixed wrong check close function in AudioContext instance.
> Fixed AudioContext.close()

- src/wavesurfer.js
Adds the `forceDecode` option to force client side decoding of the audio after download regardless if pre-decoded peaks are passed to the `.load/2` method.
This is primarily for use with `.zoom/1` to enable high fidelity rendering on zoom of instant loading pre-decoded waveforms on the UI. Without local decoding, the zoom on pre-decoded peaks is very low fidelity.
Included in this PR is alpha sorting of the `defaultParams` to make for easier reference. *I couldn't resist...*
n/a
n/a
n/a
https://github.com/katspaugh/wavesurfer.js/issues/999
> Add support for forceDecode

- _config.yml
I noticed the "Minimap" Plugin is present on the "Plugins" page but not in the Menu on the sidebar, so I added it.
> add link to minimap plugin into navigation sidebar

- plugin/wavesurfer.playlistparser.js
- user util.ajax to get file content - **ok**
- support m3u - **ok**
- check if mp3 or wav file urls set in playlist - **ok**
- return empty array if playlist type not supported or set - **ok**
- create plugin example and docs - **ok** #1019 
**playlistFile** - link to playlist file
**playlistType**
'm3u' or 'audio/mpegurl' will default to m3u
Preview:
http://codepen.io/entonbiba/pen/OpMQjR
> create playlist plugin

- src/wavesurfer.js
- src/webaudio.js
* audio context is now reused and not destroyed everytime. This allows more than 6 waves to exist.
* audio context is destroyed in the `destroy` method if `params.closeAudioContext` is set to true
* None, unless usage relied on the closing of the wavesurfer AudioContext, this needs to be done explicitly (see above)
/
* For v2/next I would use `window.WaveSurferAudioContext` since the library object isn't necessarily a global variable.
* https://github.com/katspaugh/wavesurfer.js/issues/1005
* https://github.com/katspaugh/wavesurfer.js/pull/1015
* https://github.com/katspaugh/wavesurfer.js/pull/998
* https://github.com/katspaugh/wavesurfer.js/pull/962
* https://github.com/katspaugh/wavesurfer.js/issues/374
> Readded global audio singleton, added closeAudioContext parameter

- src/mediaelement.js
Add getPlaybackRate method when using mediaelement backend.
> add getPlaybackRate method for mediaelement.js

- README.md
- example/annotation/app.js
- example/css/doc.css
- example/cursor/index.html
- example/cursor/main.js
- example/elan/app.js
- example/microphone/app.js
- example/microphone/index.html
- example/panner/index.html
- example/plugin-system/app.js
- example/plugin-system/index.html
- example/regions/app.js
- example/regions/index.html
- example/spectrogram/app.js
- example/spectrogram/index.html
- example/timeline/app.js
- example/timeline/index.html
- example/video-element/main.js
- spec/plugin-api.spec.js
- src/html-init.js
- src/plugin/cursor.js
- src/plugin/elan.js
- src/plugin/microphone.js
- src/plugin/minimap.js
- src/plugin/regions.js
- src/plugin/spectrogram.js
- src/plugin/timeline.js
- src/wavesurfer.js
- webpack.config.babel.js
* For the reasons described here: https://github.com/katspaugh/wavesurfer.js/pull/1015#issuecomment-283609182 the plugin definition format was updated.
* There is no `extends` property anymore in the plugin definition format
* All plugin classes are turned into observers when they are passed through `addPlugin`. (The plugin classes have the `@inherits {Observer}` jsdoc tag so the documentation generator gets things right.)
* Minimap instantiates a drawer using `this.drawer = wavesurfer.Drawer(el, params);` and doesn't directly inherit from drawer.
* Plugin class constructor functions are called with `wavesurfer` and `params` parameters by the core lib
* Plugin classes are exported from plugin files and have a static `create` function, which is the factory function for the plugin …
> Next: Updated plugin definition format and class exports

- src/drawer.multicanvas.js
The waveform is scrollable vertically in Chrome, however should only be scrollable horizontally, as is the case in Firefox. This can be observed here: http://codepen.io/katspaugh/pen/GozaaG, when the screen width is sufficiently reduced to result in horizontal scrolling.
> Prevent waveform vertical scrolling in chrome

- src/webaudio.js
Fix to allow old style getPeaks(length) usage with new getPeaks(length,first,last).
If no `first` and `last` parameter is set it will set the default `0` and `length-1`.
#1067
> add getPeaks background compatibility

- plugin/wavesurfer.timeline.js
I had problems with labels being things like "0.99999999999999999999" which may be extra precized, but are far from readable. Also, I think milliseconds precision is far from enough. :P
> timeline plugin: Round to milliseconds

- src/drawer.multicanvas.js
See: https://github.com/katspaugh/wavesurfer.js/issues/1014.
I also changed "entry" to "canvas" since they are canvases. And, uh, just a few styling ideas.
> "for... in" should not be used with arrays. This causes bugs!

- src/wavesurfer.js
fixes #1083 - added default start parameter `0` to work with getPeaks method.
update docs for exportPCM #1101 
```
exportPCM: function (length, accuracy, noWindow, start)
```
> fix exportPCM to return json data

- src/webaudio.js
The way the static property `audioBufferSize` is referenced (through `this`) is not valid ES2015 code and generates an error in Safari iOS at least ("IndexSizeError (DOM Exception 1): The index is not in the allowed range." since undefined is not a valid buffer size)
My fix is using the class name to reference the property but we can also use `this.constructor`
N/A
N/A
> Fixed references to static property audioBufferSize

- src/util.js
Sorry -- idk how to add to a PR.
> requestAnimationFrame addition to utils.

- src/drawer.canvas.js
Wrap drawing in requestAnimationFrame per https://github.com/katspaugh/wavesurfer.js/issues/1084.
Blocked by https://github.com/katspaugh/wavesurfer.js/pull/1107.
> Wrap drawing in requestAnimationFrame.

- src/drawer.js
`this.container.removeChild(this.wrapper);` ->
`if (this.wrapper.parentNode == this.container) this.container.removeChild(this.wrapper);`
Useful just in case. For example, I have a function that detaches everything in order for childList/removedNodes mutationObservers to fire.
> Update drawer.js -- make sure wrapper has the right parentNode.

- src/mediaelement.js
Added automatic listening to the `"play"` and `"pause"` events of the provided media element. In the current implementation, I can only control audio playback from within the context of `wavesurfer.js`. In the application I'm building, I want to have the media element be the single source of audio playback control, allowing the `wavesurfer.js` instance to be a single part of a group of visualizations rather than the main controller.
None that I am aware of
None that I am aware of
I don't know if this has any unexpected consequences but it worked perfectly for me with this simple change when running `wavesurfer.js` with the `{backend: "MediaElement"}` configuration.
N/A
> Listen to and relay play and pause events on media element

- src/drawer.canvas.js
- src/drawer.multicanvas.js
Without this change, if the zIndex of the waves is higher than the zIndex of the regions, the waves will stand out better but block the resize controls.
(Figured out how to do two files at once.)
> Add pointerEvents: none to left/right sides.

- src/drawer.multicanvas.js
Wrap drawing in requestAnimationFrame (multicanvas) per https://github.com/katspaugh/wavesurfer.js/issues/1084.
Blocked by https://github.com/katspaugh/wavesurfer.js/pull/1107.
> Wrap drawing in requestAnimationFrame (multicanvas).

- plugin/wavesurfer.spectrogram.js
Fixes #1138 
/cc @akreal @agamemnus
> Remove variable redeclarations from spectrogram

- src/drawer.js
refs #1127
Before #909, calling `drawBuffer` to redraw the wave invoked
`drawer.drawPeaks` which in turn invoked `drawer.setWidth` which
always caused the canvas to be cleared as a side effect of
`drawer.updateSize`.
In #909 `setWidth` was changed to short circuit if the width did not
change. This now causes the waveform to be redrawn on top of the
previous rendition, making the edges of the wave appear less crisp.
This change makes `setWidth`/`setHeight` return a boolean to indicate
whether changes were needed. If not, `drawer.clearWave` is called
manually. So we make sure that the previous wave is always cleared,
but do not perform the possibly performance intensive task of clearing
the canvas twice if it already happened as a side effect of
`setWidth`.
> Ensure canvas elements are cleared before redrawing

- src/drawer.multicanvas.js
I'm not entirely sure that the peaks are joined at the ends. When I zoomed all the way in, it seemed that there were gaps...
> Join ends of peaks

- src/webaudio.js
fixes #952 safari buffer undefined
```
var newBuffer = this.createBuffer(1, 4096, this.sampleRate);
```
- it creates the missing buffer based on 1 channel, 4096 samples and the sampleRate from the current webaudio context.
> fixes safari browser missing buffer when using webaudio

- plugin/wavesurfer.timeline.js
Fixes a variable redeclaration in the timeline plugin, allowing it compile in TypeScript without warnings.
> Fix variable redeclaration in the timeline plugin

- dist/wavesurfer.js
- src/wavesurfer.js
should be false by default to prevent overlapping #1147 
ref example:
https://codepen.io/newjurgen/pen/KqvYxO
> fix for forceDecode - make default set to false

- src/wavesurfer.js
This is a fork from V2 (next).
I removed the call to `.empty()`when handling the resize of the container when `responsive`is set to `true`.
This allow the playback to keep going when resizing the container.
I'm not sure about the side effects this could have in edge cases but it seems to work. Please have a look and tell me what you think.
> Fixed playback reset on resizing

- README.md
- example/zoom/index.html
- example/zoom/main.js
- src/drawer.multicanvas.js
- src/mediaelement.js
- src/plugin/timeline.js
- src/wavesurfer.js
- src/webaudio.js
Adds features and fixes that were added to the es5 branch (previously master) to the new master (previously next).
See https://github.com/katspaugh/wavesurfer.js/issues/1092
First part: https://github.com/katspaugh/wavesurfer.js/pull/1191
> Ports from es5: Part two

- src/drawer.multicanvas.js
- src/wavesurfer.js
* Fixed the waveform cut off bug #1181
* Refactored drawing functions to use `prepareDraw` where the commonly used calculations are done, the actual rendering function is passed in as a callback. This is not critical for the fix but I did it to be able to bettter understand the differences and similiarities between `drawWave` and `drawBars` and I think it definitiely cleans up those functions quite a bit.
* Sets `forceDecode` param to false by default (see #1159 – that PR was merged to *next*, not to the *master*)– ( @katspaugh can you delete the next branch so there's less confusion, thanks)
I've checked this change locally ([Demo](https://www.webpackbin.com/bins/-KsYKsFIq8FjVe-HQec_)):
* Both backends
* With and without peaks
* partialRender
* Zooming
* Resizing
* Changing pixel ratio
… …
> Waveform rendering bug

- spec/wavesurfer.spec.js
- src/wavesurfer.js
* Adds the ability to call `wavesurfer.zoom` without a parameter (or with a falsey parameter) to reset zoom state
* Adds test for the properties set in the zoom method. (Doesn't currently test the right functions are being called)
None.
None.
> Feature: Reset zoom/unzoom

- src/plugin/minimap.js
Minimap plugin `container` param only accepted an `HTMLElement` before. This change means it can also accept a selector string.
None.
None.
Fixes #1108
> Fix: Minimap container param can be a selector string

- src/plugin/minimap.js
- src/wavesurfer.js
- Minimap waveform is completely removed and readded when new audio is loaded
- Minimap playback position is correctly set a) when the plugin is added dynamically and b) "statically"
- `wavesurfer.isReady` flag is also set when using the media element backend (this fixes another media element/minimap rendering bug)
None.
None.
- fixes #617
> Fix: Minimap rendering bug(s)

- src/plugin/regions.js
* The method `ws.addRegion` that the regions plugin adds to the wavesurfer instance should return the region added
/
/
/
* Fixes #1204
> ws.addRegion should return region

- src/plugin/timeline.js
Changed for-in loop to forEach loop to avoid enumerating over Array's prototype attributes.
[#1222](https://github.com/katspaugh/wavesurfer.js/pull/1222)
> Fix:Timeline plugin incorrectly iterates over canvases

- src/plugin/regions.js
- src/wavesurfer.js
- The responsive parameter didn't accept `0` because it is a falsey value. This meant that a debounce timeout of `0` was not possible.
- Resizing function (when `responsive` is set) should only be called if `scrollParent` is not true
- Progress was incorrectly scaled when the waveform was resized. This was fixed by using the `redraw` event
- Regions didn't scale/reposition correctly when the wave was resized
- Resize also happens on `orientationchange` event
/
/
- Contains parts of #1210 
- See #1097 
- See #1146
> Fix: Bugs with responsive parameter

- src/plugin/cursor.js
- src/plugin/timeline.js
- The cursor element is no longer a child of the wave element, but of the wavesurfer container, this means it isn't moved about when the wave is scrolled (fix for #811 )
- Parameters for all styling options and a `hideOnBlur` option. (Also a `customStyle` parameter to be able to pass custom style without hassle)
- Jsdoc comments for everything
- Parameter defaults are the values which are currently being used. This update might break implementations which rely on the exact position of the cursor element in the DOM.
- Cursor element is now over the scroll bar, this has no implication for its functionality though.
/
- Tests are missing as yet
- Fixes #811 
- Contains #1233 in order to be able to build
> Fix #811: Cursor plugin refactor for improved performance and functionality

- src/mediaelement.js
- src/plugin/timeline.js
- src/wavesurfer.js
- Check whether preload attribute will be used and log warnings if not:
- `preload` is not a valid value
- `peaks` are not provided
- backend is not of type `MediaElement`
- url is not of type string
- Also updated jsdoc comments (mostly in `mediaelement.js`)
/
/
/
- Fixes the fixable part of #973 (providing informative warning messages) – Apparently the preload attribute is merely a hint to the browser and cannot prevent it from loading audio.
- Contains #1233 in order for the PR to be buildable
> Fix #973: Check whether preload attribute will be used and log warnings if not

- src/plugin/timeline.js
- Clean timeline container so consecutive file loads don't produce empty canvases
- Refactor timeline plugin to be more like the multi canvas renderer
- Performance optimisations (as described [here](https://www.html5rocks.com/en/tutorials/canvas/performance/)) for rerenders (when zooming)
- Added `labelPadding` parameter to configure the space between notches and labels
- Added `zoomDebounce` parameter to (optionally) specify a debounce timeout when zooming. (Useful for very large files
- Added jsdoc comments
/
/
- Performance gains should be more noticeable when #1220 is merged (currently there is one unnecessary timeline redraw happening when zooming)
- Contains #1233 to be able to build
- Should fix the issues in #1226 
- Should fix #967 for v2
> Fix #1226 #967: Refactoring of timeline plugin

- src/plugin/timeline.js
- src/wavesurfer.js
- removed unnecessary `this.backend.getPlayedPercents()` in `wavesurfer.seekTo` – reuses the `progress` parameter which already represents the correct value.
/
/
Also includes the build fixing commit from #1233 in order to be able build.
/
> Fix: Removed unnecessary playback position calculation in seekTo

- bower.json
- package.json
- src/mediaelement.js
- src/plugin/timeline.js
- src/wavesurfer.js
- src/webaudio.js
Adds an optional duration parameter to `wavesurfer.load` which can be used to explicitly set the duration of the audio (for both backends). This is useful to render the correct wave size in cases where the audio is not decoded:
WebAudio backend with peaks provided currently can't know the duration of the audio and thus always renders it at 100% width initially and then jumps to the correct size on first interaction (when audio is decoded) –
this can be fixed by using the duration parameter (See one use case in #1210)
/
/
- Subsequent calls of `load` overwrite the previous duration
- Once the audio is decoded (a buffer is available in `WebAudio.buffer`) its real length is used
- Improved duration parameter feature initially proposed in #1210 
- Is required to implement lazy-loading of …
> Feature: Duration parameter for the load function

- src/plugin/timeline.js
- src/wavesurfer.js
- Checks whether the progress parameter passed to `wavesurfer.seekTo` is
- a number
- not NaN
- between 0 and 1
/
/
Also includes the build fixing commit from #1233 in order to be able build.
- "Fixes" #745 by providing a readable error message.
- "Fixes" #1228
> Fix #745: Check seekTo progress parameter and return understandable error

- src/mediaelement.js
- src/wavesurfer.js
When an existing media element is reused, it makes sense to keep the media element around even when destroying the player.
> Add option to prevent removing media element on destroy

- spec/wavesurfer.spec.js
- src/drawer.js
- src/drawer.multicanvas.js
- src/wavesurfer.js
Allow updating the `waveColor`, `progressColor`, `cursorColor` and `height` options that were passed as part of the options for create.
For the wave color options, simply ensure that the wave is redrawn. For the height option, delegate to `drawer.setHeight` to handle the update.  Note that - while drawer applies the `pixelRatio` itself when initializing from `params` - `setHeight` expects a height that already has been multiplied by `pixelRatio`.
The cursor is a border on one of the wave elements. Add an `updateCursor` method to the drawer interface to allow updating the cursor related styles.
Redrawing the wave via `drawBuffer` only works correctly after #1144 has been merged.
> Add getters and setters for height and color options

- src/mediaelement.js
My earlier PR #1163 introduced 2 prettier warnings. Linting errors
apparently do not make the build fail.
> Apply prettier style to mediaelement.js

- CHANGES.md
- src/mediaelement.js
- src/wavesurfer.js
The progress might not get updated if the playback finishes while another tab is active, this happens because in modern browsers the framerate is reduced to save energy.
Fix it by updating the progress one more time using the pause event instead of relying on a high framerate.
This shouldn't break anything and is just a bugfix.
> Fix: MediaElement backend: Update progress on pause events (#1267)

- CHANGES.md
- src/mediaelement.js
- src/wavesurfer.js
- src/webaudio.js
> add support for sink id

- CHANGES.md
- src/wavesurfer.js
Check that seconds is greater than or equal to duration and not the other way around.
Just fixed a reversed condition. `this.getDuration() >= seconds` should [generally always] be true and was causing legitimate sets to skip to the end.
fixes #1292
#1046
> Fix #1292: setCurrentTime condition fix

- CHANGES.md
- src/drawer.js
Keep scrollX from going beyond the container or below 0.
The only disadvantage I see to this check happening here, is if someone is counting on special behavior when using elastic scroll beyond the container extents. In which case `drawBuffer` needs to be checking that `start`/`end` stay in bounds.
fixes #1312
> Keep scrollX in bounds

- CHANGES.md
- src/plugin/regions.js
When dragging, if mouse or region edge is near the container's edges, scroll in that direction.
Added checks, within region mouse move events, to scroll the container when within a certain threshold of the container's edges.
New region plugin options available:
`scroll` - defaults to true
`scrollSpeed` - defaults to 1
`scrollThreshold` - defaults to 10
fixes #430
> Regions plugin - Scroll when near edges of container

- CHANGES.md
- src/util/ajax.js
- src/wavesurfer.js
This pull request expands the `load(url)` method to support object initialisation. This means you will be able to add headers and other request specific properties to the load function.
Example:
```js
this.wavesurfer.load({
url: '/url/to/file.wav',
requestHeaders: [
{ 
key: "Authorization": 
value: "my-token"
}
]
});
```
Other options within `ws.util.ajax` will also be overridable.
- I've added the support for adding request headers on the the XHR request.
- I've handling the support for having the `url` variable both as a string and as a object.
- I've added a preload check whether the object as a minimum contains a `url` property.
Should not be any.
Should not be any.
We could argue that `url` is not a suitable name for the variable anymore, since it can now be a string, object and an …
> Support for XHR options

- src/util/ajax.js
Seems like there has been a mistake on how to iterate the request headers, where that has been used `for ... in` on an array. 
Now it uses the `array.forEach()` instead.
> Bugfixed the  iteration on the array

- src/plugin/regions.js
- src/util/index.js
- src/util/prevent-click.js
When creating / updating regions, cursor seeks to mouseup position.
Such behaviour should be prevented, and must be part of application logic (e.g. by listening to `region-updated` or `region-created`, seekTo start of region might be useful).
Thus, interactions with regions plugin must be ignored by drawer.
* Prevent once following click event after updating or creating a region with a preventClick util function
* Added mouse up listener on body when creating region to stop resize if cursor leaves waveform
* Do not fire region update-end event if nothing changed
The only way to prevent click events to "bubble" after a `mouseup` is to capture following click event from body (or a parent to the listener), and stop its propagation.
So i added a preventClick util to expose it to future …
> Regions Plugins - prevent Click when creating / updating region

- src/wavesurfer.js
The isReady attribute is set to false at the creation of a wavesurfer. Then, It is set to true when a song is loaded but it is never set to false when emptying the wavesufer. As a result, after the first song is loaded, isReady return true even if the wavesurfer is empty.
> Update isReady attribute

- src/plugin/cursor.js
in cursor plugin
move variable wrapper to this,
else when call destroy method its throw error
cannot read property removeListener of undefined
> fix cursor plugin destroy

- example/angular-material/wavesurfer.directive.js
In the Angular Player example, when the time was suppose to hit a new minute and display 01:00 or 02:00 it would display 00:00 for one second before displaying 01:01 or 02:01. By changing the format function it now displays each minute properly and the length is the actual file length.
> Change the time format for seconds from ceil to floor 

- CHANGES.md
- src/plugin/microphone.js
This PR just makes the microphone plugin work on Edge: the audio data received from onaudioprocess is first copied to a local AudioBuffer which is passed on instead of the event.inputBuffer. Note that there is a lot of blinking whenever a new buffer is received.
There are no breaking changes.
fixes #627
> plugins: fix microphone plugin on MS Edge 

- karma.conf.js
- src/plugin/minimap.js
Fixes some styling issues with the minimap plugin, the height and widths were not being calculated correctly. Also adds support while zooming in on the waveform to update the minimap.
Ignore the weirdness near the end of the gif with the zoom jumping out, that's just my terribly buggy zoom code (outside of wavesurfer) 😆
Nothing
Nothing
Nothing yet, maybe I'll find some more stuff to fix later on :) The library is awesome, really enjoying how easy it is to use overall.
fixes #290
> Fix minimap styling issues and add support for zooming

- src/wavesurfer.js
* The PluginClass (base class defined in src/wavesurfer.js) has `constructor(ws, params)`
* \*Plugin (concrete classes defined in src/plugin/*.js) have `constructor(params, ws)`
* The WaveSurfer object instantiates plugins with `new *Plugin(params, ws)`
* The PluginClass has `constructor(params, ws)`
None
None
None
None
> Fix order of arguments for PluginClass.constructor

- src/plugin/timeline.js
Short description of changes:
Add handling for duration parameter to Wavesurfer Timeline plugin. The code I added to the renderCanvases function favors the duration parameter over this.wavesurfer.backend.getDuration()
Related Issues and other PRs:
fixes #1460
> plugins: add duration parameter handling to timeline plugin

- spec/wavesurfer.spec.js
- src/webaudio.js
Return empty array from `getPeaks` when `this.buffer` is not set.
none?
none?
Fixes #1529 
Fixes #1507
> Fix computing peaks when buffer is not set

- src/webaudio.js
When using "WebAudio" in Safari the "audioprocess" event doesn't get fired anymore once you pause/play the current song or load a new one into your wavesurfer object preventing the following piece of code to be executed:
```
this.backend.on('audioprocess', time => {
this.drawer.progress(this.backend.getPlayedPercents());
this.fireEvent('audioprocess', time);
});
```
This commit fixes the bug, so it is not needed anymore to use "MediaElement" on Safari as a workaround (which has its own drawbacks).
This fix was also discovered and reported by @Joudee but apparently overlooked and not included in a PR.
No
No
Afaik fixes the bug entirely with no additional work left to be done.
fixes #1215 
fixes #1367 
fixes #1398
> fix removeOnAudioProcess for Safari

- src/plugin/regions.js
- src/wavesurfer.js
- src/webaudio.js
Pre-generated peaks waits for the audio length, either from loaded audio or from explicitDuration. This PR adds explicitDuration as an argument for the WebAudio constructor. This allows it to be defined up front.
I've also updated the regions plugin initialization to make use of this information so the "backend-created" event is used to add regions, rather than the "ready" event which only fires when a song has finished loading.
> regions plugin: display regions before file load

- CHANGES.md
- spec/plugin-api.spec.js
- src/wavesurfer.js
returns a map of pluginsthat are currently initialised.
> add wavesurfer.getActivePlugins()

- CHANGES.md
- src/wavesurfer.js
make it a public boolean as it is, and was, being used:
```console
$ grep -Rn 'isReady' src/
src//plugin/regions.js:658:        if (this.wavesurfer.isReady) {
src//plugin/timeline.js:189:        if (this.wavesurfer.isReady) {
src//plugin/spectrogram.js:334:        if (this.wavesurfer.isReady) {
src//plugin/minimap.js:177:        if (this.wavesurfer.isReady) {
```
fixes #1597
> define wavesurfer.isReady as public boolean

- CHANGES.md
- src/webaudio.js
As [requested here](https://github.com/katspaugh/wavesurfer.js/issues/1614#issuecomment-481666875).
fixes #1614
> Use fake AudioContext when not supported

- CHANGES.md
- build-config/fragments/common.js
- package.json
- src/drawer.canvasentry.js
- src/drawer.multicanvas.js
This PR adds a `CanvasEntry` class used by the `MultiCanvas` renderer. Previously the renderer used simple objects to store the canvas and rendering context in, this PR creates a dedicated class for these canvases. This way it should be easier to eventually implement `OffscreenCanvas` support (#1600).
Also disabled eslint in webpack, because it's really annoying to fix lint errors while you're working on wavesurfer.js. eslint will run when you try to commit the changes, a much better moment to fix lint errors.
> refactor: add drawer.canvasentry

- package.json
Added a new npm script "prepare" in the package.json, which simply redirects to the build-script. The prepare script is described by npm as follows:
> Run both BEFORE the package is packed and published, on local npm install without any arguments, and when installing git dependencies (See below).
https://docs.npmjs.com/misc/scripts
This is sometimes required, if the dependency is not installed over npm directly but over github.
None
None
None
None
> Added npm prepare script

- src/drawer.canvasentry.js
fix for barWidth option not working after canvasEntry refactor, arguments were missing in the call to fillRectToContext
fixes #1628
> add missing arguments to fillRectToContext

- src/wavesurfer.js
Only skip to end of audio if seconds passed to setCurrentTime is longer than the duration, not shorter. This is fixed on master but not on the es5 branch.
> Fix comparison of seconds and getDuration in setCurrentTime

- src/plugin/cursor.js
- change type of this.showtime in cursor plugin from Boolean to HtmlElement
- fix typo in comment, add missing l in mili
> fix showtime jsdoc type, fix typo in comment

- src/plugin/spectrogram.js
I noticed that when handling click events performed in the spectrogram, the click position/progress was always evaluating to 0. After some investigation, I realized that the property `this.scrollWidth` did not exist in the context it was being used (spectrogram.js, line 433), and I believe the correct property name is actually `this.width`, since after that modification the position value was aparently evaluating correctly.
> spectrogram plugin: fix variable name in click handler

- src/plugin/minimap.js
When drawing regions in the minimap plugin, the position calculated is incorrect on 4k or retina screens
None
None
https://github.com/katspaugh/wavesurfer.js/issues/354
> minimap plugin: fix left/width calculations for regions on retina/4k screens

- CHANGES.md
- example/rounded-bars/index.html
- example/rounded-bars/main.js
- src/drawer.canvasentry.js
- src/drawer.multicanvas.js
- src/wavesurfer.js
Added an optional `barRadius` parameter for specifying the radius of rounded bars. Added `drawRoundedRect` method for rendering rounded bars on Canvas.
No BC break.
No BC break.
fixes #953 
If this will be merged I will document this feature in `gh-pages` branch
> Waveform with rounded bars

- src/plugin/regions.js
Currently start handler is located inside the region while end handler is outside of the region boundary.
PR solves the issue by relocating the end handler to be a part of whole region block
No breaking changes
No breaking changes
-
-
> regions plugin: change position of region end handler

- src/drawer.js
support dblclick event listener
add `dblclick` (and `click`) to docs wavesurfer events
fixes #1764
> add dblclick event listener to wavesurfer wrapper

- src/plugin/regions.js
In 804334d63e36f88b5340aa8faac2d0db5adf5acf, the css style of the right region resize handle was changed to `right: 0`, but the element in question already had a `left: 0` style.  This means that the drag handles for the region were basically in the same place.
> style right and left handles of region plugin independently

- src/plugin/regions.js
I've had the need of late to start playing a loop defined in the region plugin in the middle of the loop.
(fyi if you're interested, https://mixmastermiles.com/)
> regions plugin: add start argument to play and playLoop methods

- src/plugin/regions.js
I've been heavily using the regions plugin in a project i'm playing with.  One feature I definitely needed (for my UI's sanity) was to limit the number of regions a user could create (to 1, in my case).
> regions plugin: add maxRegions option to limit max nr of created regions

- src/mediaelement.js
- src/wavesurfer.js
- src/webaudio.js
When someone is playing back a loop or region, this allows for moving the loop end-point while playback is happening.
If you like I can also code that behavior into regions.js.  currently I'm moving the loop end point in external code.
> allow changing the stop-point of wavesurfer during playback

- docs/options.html
on my browser the properties name on the options pages wrap ugly like this: 
due to some odd bootstrap css around `<code>`.
> document barMinHeight.  Also some css to stop prop names from wrapping.

- CHANGES.md
- spec/wavesurfer.spec.js
- src/wavesurfer.js
Sometimes it can take a while before `JSON.stringify`, used in `exportPCM`, finishes, so return a Promise that resolves with data.
Also added missing `end` parameter to `exportPCM`.
I'm aware this is not backwards-compatible but not sure how else to fix/improve this issue.
fixes #1728
> return Promise from wavesurfer.exportPCM

- src/plugin/regions.js
As it's invalid (I noticed when bundling with rollup).
Reproduce in a browser with something like the following:
```html
<script type=module>
import * as util from './util.js';
util.a = 1;
</script>
```
> regions plugin: don't assign to module object

- src/plugin/regions.js
Currently we can set the handleColor for a region inside CSS, while this is great, it does not allow the user to set the handleColor dynamically. 
- I currently moved out the creation of `handleLeft` and `handleRight` to the render function instead of inside the resize conditional, just so that we don't have to create them again, I am not sure whether or not this has a performance impact.
**Notes**
- Added a new handleColor attribute to the Region constructor
- The regular CSS solution still works as you would expect
> regions plugin: allow setting the handleColor inside addRegion

- src/plugin/regions.js
**Now there can be specified `channelIdx` param to draw region on specific channel**
```
plugins: [
WaveSurfer.regions.create({
regions: [
{
start: 1,
end: 5,
loop: false,
color: 'hsla(400, 100%, 30%, 0.5)'
},
{
start: 7,
end: 9,
loop: false,
color: 'hsla(200, 50%, 70%, 0.4)',
channelIdx: 1
}
]
})
]
```
Height of region is controlled by 2 parameters, `regionHeight` and `marginTop`:
```
this.regionHeight = '100%';
this.marginTop = '0px';
let channelCount = this.wavesurfer.backend.ac.destination.channelCount;
if (channelIdx >= 0 && channelIdx < channelCount) {
this.regionHeight = Math.floor((1 / channelCount) * 100) + '%';
this.marginTop = this.wavesurfer.getHeight() * channelIdx + 'px';
}
```
Default behavior(if parameter is omitted) draws whole height.
> regions plugin: add option to select specific channel to draw on

- src/plugin/regions.js
**Prevent from attaching multiple event handlers to drag selection action, in a scenario where drag selection is enabled multiple times in a row.**
The simplest solution was applied: disabling drag selection before enabling it. I've tested a few other possible solutions, but this was the shortest and the best. One of the other possible solutions was setting a flag indicating that drag selection is already enabled and returning from the `enableDragSelection` immediately, but this unfortunately also prevents from updating drag parameters by simply calling `enableDragSelection` again with new parameters.
The main cause why this issue even happened is because of using "arrow functions" for event listeners. When `addEventListener` is used with **the same** event handler, the previous handler …
> regions plugin: disable drag selection before enabling it

- src/plugin/regions.js
This PR improves the stylability of the region handles. Previously (since version 3.3.0) it was only possible to set a background-color. This feature was made possible by #1798. Other styling properties could not be set on the region handles.
This PR makes it possible to:
1. Set any styling property on a handle. As discussed [here](https://github.com/katspaugh/wavesurfer.js/issues/1838#issue-544401172).
2. Disable all JS-styling of a handle. This way styling can be done in CSS. As discussed [in point 1 here](https://github.com/katspaugh/wavesurfer.js/issues/1838#issuecomment-570312988).
None, as far as I can see. It should be compatible with v3.3.0 / PR #1798, but please check my comment [there](https://github.com/katspaugh/wavesurfer.js/pull/1798#issuecomment-570084267).
None, as far as …
> regions plugin: improve handle style support

- src/plugin/regions.js
This PR adds support for a context menu event on a region in the regions plugin. It contains an option to disable the native context menu from being opened (`preventContextMenu`, defaults to false).
Fixes #1842.
The functionality was approved by @thijstriemstra [here](https://github.com/katspaugh/wavesurfer.js/issues/1842#issuecomment-570937396).
> regions plugin: add support for a context menu event on a region

- CHANGES.md
- src/drawer.multicanvas.js
As discussed [here](https://github.com/katspaugh/wavesurfer.js/issues/1884#issue-586311889), this is a workaround for #1884.
fixes #1884
> Use requestAnimationFrame for clearWave

- src/drawer.canvasentry.js
Fix Unable to get property 'toLowerCase' of undefined or null reference in IE11
Check if constructor name exist before converting it to lowercase, else use hardcoded value 
none
none
none
fixes #1771
> Fix Unable to get property 'toLowerCase' of undefined or null reference in IE11

- docs/options.html
barMinHeight was mistakenly labelled barHeight on the options page.
No
No
None
None
> Corrected "barMinHeight" option typo in documentation.

- src/plugin/elan.js
This fixes a bug where undefined Elan `params.tiers` would lead to an error, thus making the parameter truly optional. #1910 
N/A
N/A
> Elan plugin: optional params.tiers (#1910)

- src/plugin/regions.js
This PR fixes the issue described in Issue #1925 where a click on the region is ignored by the wavesurfer interact click implementation. This behavior can be undesirable and this PR fixes that.
fixes #1925 
None
None
Possible improvement is to not stop propagation for when the current behavior is desirable.
The way this could be implemented is by passing the browser event with the region in the handler callback and letting the callback implementation can determine if stopping propagation is needed or not.
Issue #1925 
https://stackblitz.com/edit/js-paffsu?file=index.html
1. Play the reproduction above
2. Click on the region during playback
3. The region will not be played but the playback will seek to where was clicked
> Regions plugin: fix click propagation issue

- src/plugin/regions.js
If a region is in loop, try to loop another region at this time, the `out` event will still occur, causing the jump to fail, and will bind multiple events, browser may crash.
In order to solve this problem, I added a judgment in the `playLoop()` function, only looped when the play time was in the current region.
None
None
https://wavesurfer-js.org/example/annotation/index.html
1. Hold down shift and click on a region to start loop.
2. Click any region before the region to reproduce the bug.
> Regions plugin: fix switch loop region

- CHANGES.md
- src/plugin/regions/index.js
- src/plugin/regions/region.js
Adds timeformatCallback functionality to Regions
fixes #1948
> regions plugin: ability to specify time format using timeformatCallback

- example/plugin-system/custom-plugin/CursorCustomPlugin.js
Updated example of plugin inheritance because after removing all private methods of plugins, a custom plugin can be extended without duplicating code related to private methods.
#1928
> Plugin inheritance example updated

- CHANGES.md
- example/split-channels/app.js
- example/split-channels/index.html
- src/drawer.multicanvas.js
- src/wavesurfer.js
Our project would like to allow the user to filter out channels from the audio for playing/viewing. The filtering for playing will be done via setFilters. This pr is to add the rest via a new parameter **splitChannelsOptions** and a new method **setFilteredChannels**.
1) Add splitChannelsOptions parameter that applies if splitChannels is true.
Contains the following options:
overlay - draws channels on over each other when splitting
channelColors - defines colors for channels individually
filteredChannels - channel indices to filter (do not draw on the waveform)
2) Add setFilteredChannels method to update the filteredChannels param.
3) Update split channels example to include info on the above.
none
none
The splitChannelsOptions currently only works with drawWave.
coloring: …
> When splitting channels, allow coloring and filtering of channels

- CHANGES.md
- src/plugin/minimap.js
Since `minimap` and `regions` plugin are related when the `showRegions` option is setted to `true`, there may be errors when one plugin is destroyed before the other. In particular, when the `minimap` plugin cannot find the `drawer` of regions. So the error which occurs is this:
Check il the `drawer.wrapper` exists before rendering regions.
> minimap plugin: added check for drawer presence

- src/plugin/spectrogram.js
It turns out, if the parent WaveSurfer instance is not ready by the time `destroy()` is called, this line will throw an error.
Reason being https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/spectrogram.js#L306 shows `this.drawer` is only assigned when `this._onReady` is called.
None
None
> spectrogram plugin: perform null check when removing scroll listener

- CHANGES.md
- src/drawer.canvasentry.js
- src/drawer.js
- src/drawer.multicanvas.js
Removed private methods from wavesurfer drawer, so a new one can be created, inheriting the existing ones, and overriding only the necessary features.
Removed all private clauses from `drawer.js`, `drawer.canvasentry.js` and `drawer.multicanvas.js`.
> Drawer: removed private methods 

- CHANGES.md
- src/mediaelement.js
- src/wavesurfer.js
`wavesurfer.js` currently handles muting the media by setting the backend's volume to 0 and remembering the previous value, **but** it also checks whether the backend maintains muting state and uses it to override its own. This is currently used by the `MediaElement` to make wavesurfer aware of muting/volume changes performed directly on the `Audio` element, but muting through `wavesurfer.js` itself triggers a backend volume change without changing the backend's `isMuted` state, so the end result is the volume switching to 0 and the media being unmuted, leading to inconsistent and erratic behavior.
This PR adds an optional `setMute` method to backends so that the `MediaElement` backend can handle muting by itself.
None.
None (the `setMute` method is optional so that other backends do not …
> Fix muting behavior with the MediaElement backend

- src/wavesurfer.js
#1966 incorrectly set wavesurfer object's `isMuted` to `true` even when it's supposed to be `false`.
This is not an issue in practice, as it gets correctly re-set by the `volumechange` handler, but this is wrong anyway, and as a result make the tests fail.
> Fix setMute setting incorrect isMuted

- CHANGES.md
- src/mediaelement-webaudio.js
- src/webaudio.js
This fixes a condition where Safari was not playing with mediaelement/webaudio.  It seems to implement the webaudio spec slightly differently than chrome and requires that you call AudioContext#resume().  
I also rewrote the header comment into more natural english.
refs #1531
> Mediaelement safari fixes

- CHANGES.md
- src/util/observer.js
due to the odd way the RegionsPlugin pulls in the methods in util.Observer, it needs to setup a private array or it crashes in `fireEvent`.
I could also fix this in `Observer` by checking for the existence of the array.  I dunno.  both seem odd.
fixes #1975
> guard against null _disabledEventEmissions in Observer#fireEvent

- package.json
GitHub uses this to display the package in the repo page sidebar.
> Add publishConfig

- CHANGES.md
- src/plugin/regions/region.js
`regions` plugin has doubled loop playback logic.
**First** can be found here, binding `out` event:
```js
/* Bind audio events. */
bindInOut() {
// ...
/* Loop playback. */
this.on('out', () => {
if (this.loop) {
this.wavesurfer.play(this.start);
}
});
}
```
https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/regions/region.js#L336
**Second** is in `playLoop()` method:
```js
/**
* Play the audio region in a loop.
* @param {number} start Optional offset to start playing at
* */
playLoop(start) {
const s = start || this.start;
this.wavesurfer.play(s);
this.once('out', () => {
const realTime = this.wavesurfer.getCurrentTime();
if (realTime >= this.start && realTime <= this.end) {
return this.playLoop();
}
});
}
```
https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugi …
> regions plugin: improve loop playback logic

- CHANGES.md
- src/drawer.multicanvas.js
constantly changing the width of the multi-canvas `progressWave` element triggers a layout pass in the browser.  This doesn't seem to be a huge problem for Chrome, but in Safari on mac it's worth quite a hunk of performance.
This is Safari pre-patch  (I played the whole file on /example/html-init/ for these tests):
Safari post-patch:
Chrome seems to jitter more and benefit less, but note the ~10% of rendering that we seem to save:
pre-patch:
post-patch:
would love to know if I'm missing anything with the logic here or if other people can run benchmarks and see if this feels like a win.
> performance: use clip-path css instead of width

- CHANGES.md
- src/plugin/regions/region.js
Added `updateHandlesResize` method to remove cursor `col-resize` style when updating region with resize setted to false, and to restore `col-resize` when is setted to true
`updateHandlesResize` method 
fixes #1963
> Regions: remove cursor col-resize when disable region resizing

- CHANGES.md
- src/drawer.multicanvas.js
this killed off the cursor functionality.  we're using the right-hand-border of the progressWave to show a "audio cursor" element.
It's a pity, it was worth some nice performance in safari.  I poked at doing a `canvas` based cursor but didn't get very far.
fixes #1992
> Revert "performance: use clip-path css instead of width (#1983)"

- CHANGES.md
- src/wavesurfer.js
PR #1969 removed the call to MediaElement#load, but this means that we weren't properly triggering the waveform to render in the case where peaks were provided.
> add a call to drawBuffer in `loadMediaElement`

- CHANGES.md
- example/regions/app.js
- example/regions/index.html
- src/plugin/regions/region.js
- Fix region onResize code not checking minLength, which allowed you to "push" regions while dragging them past the point where they should stop shrinking. See related issue for better description.
- Fix handles CSS in region example. They were set to width: 1% which made them scale with the size of the region, and they became invisible when the region was small enough. Now they're always 2px.
None
None
The resizing behaviour in general could do with some improvements. For example I don't think you should be able to drag regions to size 0, because then you can't grab them again and you lose them. Maybe regions could have a default minLength: 0.1 or so.
Other possible future enhancements:
- minLength is not documented in the example page.
- minLength/maxLength don't seem to be used a lot …
> regions plugin: fix region ignoring minLength when being resized

- src/util/observer.js
Complete a todo note: initialize Observer handlers in constructor and remove checks in `un` and `on` methods, this.handlers can never be null anymore.
Also clean up a little bit (=== instead of ==, jsdoc and shorter arrow functions)
> Code cleanup for Observer class

- CHANGES.md
- src/wavesurfer.js
Cancel the current ajax request's ReadableStream during wavesurfer destroy to prevent unhandled AbortError (which was breaking tests).
Firefox only bug?
Closes #2042
> Fix for unhandled AbortError thrown during cancelAjax

- CHANGES.md
- src/util/observer.js
This reverts commit 590d9ccc96f6c69090849f2e5cfb4587da647ee5.
Fixes #2067 (this.handlers is undefined)
> Revert "Code cleanup for Observer class (#2041)"

- CHANGES.md
- src/wavesurfer.js
When making calls to the `seekTo` method while the audio is playing, we were experiencing a issues with console errors and performance (to the point of the UI becoming completely unresponsive in the case of high-frequency seeking) because of unnecessary calls to `start` and `pause` inside that method.
Making the `seekTo` method `async` and awaiting the calls to `pause` and `start` inside solved the errors and the performance hit for low-frequency seeks (less than ~3 seeks per second) but wasn't good enough for higher-frequency seeking due to too much delay to resolve the promises.
We finally decided to remove those calls altogether, because they appear to be redundant. They were first introduced in #918, and supposedly solved an issue with backward seeking on `MediaElement`, which I …
> Fix performance issues with seeking while audio is playing

- karma.conf.js
- spec/drawer.spec.js
- src/webaudio.js
headless is broken since Chrome 83 for some reason.
> catch unhandled Promise in decodeAudioData

- CHANGES.md
- example/split-channels/app.js
- example/split-channels/index.html
- spec/util.spec.js
- src/drawer.multicanvas.js
- src/util/absMax.js
- src/util/index.js
- src/wavesurfer.js
Introduced new splitChannelsOption parameter relativeNormalization, that allows wavesurfer to normalize channels while keeping them proportional to each other. Currently normalize normalizes each channel independently, so it's impossible to visually tell when a channel is louder than the others after normalization.
Also fixed assignment of default parameters to splitChannelsOptions, so partial options won't cause bugs anymore. 
None
None. Added parameter to MultiCanvas.prepareDraw that can be left undefined in order to prevent breaking current calls. 
Added esdoc documentation for splitChannelsOptions. Still need to update gh-pages if PR is accepted
> Introduce relativeNormalization option for split channels rendering

- CHANGES.md
- src/plugin/spectrogram/index.js
Use `ImageData` to perform the pixel-by-pixel drawing operation instead of calling `fillStyle` and `fillRect` thousands of times since that translates to thousands of DOM operations within one frame.
Removed `const length` because it was unused in the method.
none
none
Since there are no automated tests for the spectro plugin, I manually performed the following steps with and without the changes:
1. Set the device pixel ratio (1, 2, and 3) using Chrome dev tool's Device Mode
2. Load the spectro example page
3. Right click the spectro canvas to save image (need to turn off Device Mode to do this step)
I did this for both the mono and stereo test audio files. Here are the saved images for you to compare: 
[Compare Spectro.zip](https://github.com/katspaugh/wavesurfer.js/files/5649398/Compare. …
> spectrogram plugin: Use ImageData to draw pixel-by-pixel

- CHANGES.md
- src/webaudio.js
webaudio backend: set playback rate modifying directly the playback property of the source node. Removed invocation to pause and play
None
none
fixes #2113
> [setPlaybackRate] Webaudio backend

- docs/options.html
Updated gh-pages options documentation to include `splitChannelsOptions` options, including `relativeNormalization` to be added in 4.3.0
n/a
n/a
*Should only be merged after npm is updated to 4.3.0* (#2121)
I wasn't sure of what was the preferred format for documenting nested options. I opted to keep each option in a separate row in the table but I'm happy to revise if someone has a better approach. 
https://github.com/katspaugh/wavesurfer.js/pull/2108
> splitChannelsOptions options gh-pages docs for 4.3.0

- CHANGES.md
- src/wavesurfer.js
Revert the changes from #2045 but only for `WebAudio` backends.
Fixes #2149
> Fix seeking issue for WebAudio backends

- CHANGES.md
- src/plugin/regions/index.js
It is difficult to set a region border close to the start or end of a wavesurfer. The intention here is that when the mouse leaves the wavesurfer, the region being adjusted stays at the most recent mousemove position instead of following the mouse after mouseup outside the wavesurfer.
> regions plugin: stop dragging region when mouse exits wavesurfer div

- CHANGES.md
- karma.conf.js
- spec/webaudio.spec.js
- src/wavesurfer.js
The WaveSurfer.load function's documentation says that the url parameter can be a string or a HTMLMediaElement, but when using the `WebAudio` backend, the loadBuffer function will assume the URL is always a string, and send incorrect HTTP requests like this:
Technically this affects the external API, but instead of breaking existing code, it will fix currently broken code.
> WaveSurfer load() should accept HTMLMediaElement when using WebAudio

- CHANGES.md
- spec/wavesurfer.spec.js
- src/wavesurfer.js
> ensure webaudio is removed from ram/cpu usage

- build-config/fragments/dev.js
Added rootDir const to webpack dev config. Should resolve issue with build we discussed on #2167
> build: remove publicPath from webpack dev config

- CHANGES.md
- build-config/fragments/dev.js
- src/drawer.multicanvas.js
#2161 
When setting overlay: true on split channels the height of the waveform becomes equal to a single channel height but does not overlay the second channel. 
The issue is that the offsetY value is set based on height multiplied by the drawIndex or default to zero. In this case we should check for the splitChannelOptions.overlay and set the offsetY to zero regardless of the drawIndex.
> Split channels: overlay param now properly displays a single canvas

- faq/index.html
BBC's audiowaveform is generating a interleaved version when using the --split-channels flag, see https://github.com/bbc/audiowaveform/blob/master/doc/DataFormat.md . wavesurfer.js, however, seems to expect an separate array for each audio channel for the externally generated peak data. This updated script should generate appropriate peak data for multichannel files (8 channels is currently the maximum supported number by BBC's audiowaveform).
None
None
Tested with 1 - 8 channels for different backends and it seemed to work as expected.
#356, #1954
> Adding deinterleaving to scale_json.py script in FAQ to support multichannel peak data generated by audiowaveform

- CHANGES.md
- src/webaudio.js
The previous check was not sufficient and broken in some cases.
Related webkit commit: https://trac.webkit.org/changeset/265352/webkit
```
BaseAudioContext.decodeAudioData() should return a Promise as per:
- https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata
 
Behavior is unchanged for prefixed WebKitAudioContext.decodeAudioData() to ensure
backward compatibility.
```
`window.webkitAudioContext` can be flipped on/off using the `Experimental Features > Modern WebAudio API` option in Safari.
> webaudio: fix decodeAudioData handling in Safari

- CHANGES.md
- example/markers/app.js
- src/plugin/markers/index.js
markers placed at the beginning or the end of a region weren't properly overflowing, instead they pushed the wavesurfer container to be wider and that messed up calculations when seeking around a waveform.
Does this need a CHANGELOG?  not sure if you've released the marker stuff into the wild yet.
> markers plugin: markers at the begin/end of file were screwing up seeking

- CHANGES.md
- src/plugin/regions/index.js
- src/plugin/regions/region.js
Improvements addressing 2 minor annoyances (including 1 legit bug fix):
1. Fix a bug that prevented firing mouseup to end a region drag if the user clicked and dragged a region handle and released the mouse button outside of the browser window. Fixed by attaching the `mouseup` event listener to `document` instead of `document.body`.
2. Added new `RegionParams` option `showTooltip` allowing disabling the `title=...` tooltip (just because I found the unstyleable tooltip obtrusive and got tired of having to do `element.removeAttribute("title")` all the time).
Nothing. The default value for the new `showTooltip` parameter is the old behavior.
Nothing
> regions plugin: drag bugfix & showTooltip parameter

- .github/workflows/publish.yml
- README.md
As discussed in #2191, let's automate the publishing of our NPM package.
When a pull request is merged to the protected `release` branch, a new version of the package will be published. Ideally, we should choose the rebase merge option so that the `release` branch is identical to master.
Here's the first successful job: https://github.com/katspaugh/wavesurfer.js/runs/2037945086?check_suite_focus=true
> Publish to NPM via GitHub Actions

- .eslintrc.js
- example/audio-element/main.js
- example/elan/app.js
- example/equalizer/main.js
- example/main.js
- example/media-session/app.js
- example/minimap/app.js
- example/mute/app.js
- example/panner/main.js
- example/playlist/app.js
- example/plugin-system/app.js
- example/regions/app.js
- example/rtl/main.js
- example/spectrogram/app.js
- example/split-channels/app.js
- example/timeline-notches/main.js
- example/timeline/app.js
- example/trivia.js
- example/video-annotation/main.js
- example/video-element/main.js
- example/zoom/main.js
many of them are sharing a wavesurfer instance with `trivia.js` via a global variable.  I can't say this is the best idea, but this is at least explicit about it.
If there's a better approach I'm all ears, I looked down the road of timeline.js fishing out the wavesurfer instance from the DOM but didn't see an easy way.
> get examples working again

- .github/workflows/publish.yml
@thijstriemstra thanks for the docs link, it worked nicely 👍 
I've also reorganised the steps a bit, so that each command has a separate title.
Here's the build that published release 4.4.0: https://github.com/katspaugh/wavesurfer.js/runs/2271665459?check_suite_focus=true
Closes #2231.
> Automate GitHub releases

- UPGRADE.md
Ref: https://github.com/katspaugh/wavesurfer.js/commit/a262e6993ffded2f06b65bb4ac373312e9e6aff8#commitcomment-50513905
> docs: add upgrade instructions for 5.0

- CHANGES.md
- src/plugin/regions/region.js
Recent change to support vertical orientation in the Regions plugin introduced a bug that made the rollover cursor for region handles always show the vertical cursor even when in non-vertical mode.
Nothing
None
> regions plugin: cursor orientation bugfix

- CHANGES.md
- src/plugin/markers/index.js
Changes: When you click `labelDiv`, the `marker-click`event of wavesurfer is triggered (not previously).
Reasons:  In fact, when I want to do more when I click on marker, event is necessary
No
No
> markers plugin: trigger click event on wavesurfer

- plugins/markers.js
**Title:** fix: wrong resource path in marker plugin doc
Sorry to put the wrong link.
https://github.com/katspaugh/wavesurfer.js/pull/2300
> examples: fix wrong url path in markers example

- plugins/markers.html
had "id" instead of "time"...also specified "in seconds" since there was no telling if it was milliseconds or what
> Marker time option typo

- CHANGES.md
- src/wavesurfer.js
- src/webaudio.js
Fixes
`Failed to execute 'stop' on 'AudioScheduledSourceNode'`
and
`Cannot read property 'decodeArrayBuffer' of null`
(both timing / state issues)
Adds the necessary checks to stop errors from happening.
none
none
none
fixes #2279
fixes #1473
> improve error handling in ws.decodeArrayBuffer and WebAudio backend

- CHANGES.md
- src/plugin/regions/region.js
Add new `direction` and `action` fields to `region-updated` event params. That is going to help to understand in what direction is moving or resizing a region and what exactly happened.
`direction` can be in 3 states: `null`, `start` and `end`
`action` can be `drag` or `resize`
```
wavesurfer.on('region-updated', function(region, { direction, action }) {
console.log(region, direction, action);
});
```
No breaking changes
No breaking changes
> regions plugin: add direction and action to region-updated event params

- src/plugin/regions/region.js
Event param `direction` on region resize is not correct. 
`start` means `left`
`end` - `right`
#2339
> regions plugin: fix region resize event direction

- CHANGES.md
- example/gradient-fill-styles/index.html
- example/gradient-fill-styles/main.js
- package.json
- spec/wavesurfer.spec.js
- src/drawer.canvasentry.js
- src/wavesurfer.js
Added feature to pass an array of colors into the waveColor and progressColor parameters.  Edited the setFillStyles function to check if the provided argument is a string or an object.  In the case of an object, a linear gradient is created, with each item in the array added as a color stop.
Not sure.
None, as it runs the check to see if it is a string, therefore should be backwards compatible.
If this feature is integrated, I would eventually like to integrate the ability to pass images and even a video as the wave background.
> Support for linear gradients: add additional type to waveColor and progressColor parameters

- CHANGES.md
- src/plugin/regions/region.js
Increased the `region` element's hardcoded `z-index` from 2 to 3 to fix stacking glitches.
For a demo of one the bugs this aims to fix, go to https://wavesurfer-js.org/plugins/regions.html and advance the playhead to the middle of the waveform. You'll see the 2 regions go from being above the waveform to being behind it. Then drag the blue region's end handle position to be past the playhead. You'll see the end handle of that region now appears above the waveform while its start handle appears behind it.
This also fixes stacking issues with zooming when regions are present, because as the zoom level increases new `canvas` elements with a hardcoded `z-index` of 2 are appended to the same parent as the regions, which can cause regions to appear to jump behind and in front of the waveform …
> Regions plugin: increase z-index to fix visual inconsistencies

- CHANGES.md
- src/drawer.js
- src/wavesurfer.js
Add option `hideCursor`.
- hides the cursor if set to true, by default it will always show.
fixes #2366
> Add option hideCursor

- CHANGES.md
- example/split-channels/index.html
- spec/wavesurfer.spec.js
- src/wavesurfer.js
Add optional parameter `channelIdx` to these methods
- `setWaveColor`
- `getWaveColor`
- `setProgressColor`
- `getProgressColor`
> Add optional parameter channelIdx to colors methods

- CHANGES.md
- example/markers/app.js
- src/plugin/markers/index.js
Add drag & drop functionality on markers defined as draggable.
Allow to set markers as draggables to allow to drag&drop it, the updated time will be set in the marker time property and a new *marker-drop* event will be fired.
None, only markes set as draggable can be dragged
None
Update plugin doc 
None
> markers plugin: support for drag & drop functionality

- CHANGES.md
- src/plugin/regions/index.js
**Title:** Fix edgescroll for regions created after region plugin
Looking for a value for edgeScrollWidth for a region, either from plugin params or a default value, was only happening for regions specified in the plugin params; it now happens for all regions. The consequence of it not being set was that the logic for doing edgescrolling was doing calculations with `undefined`, and so never doing any scrolling.
None
None
fixes #2401.
The problem was noticed in the course of pull request #2294.
> regions plugin: ensure edgeScrollWidth is set

- CHANGES.md
- src/plugin/regions/index.js
Currently when wavesurfer is destroyed the `RegionPlugin` will emit a `region-removed` event the same way it would when a user removes a region. This can be confusing in applicaton code since `region-removed` can emit without users interacting with the plugin.
If anybody relied on `region-removed` being emitted during plugin destruction this would break that functionality.
Spent some time looking around at different ways to handle `RegionPlugin.destroy()` without emitting `region-removed` in the call chain. I came across `setDisabledEventEmissions` and that seems like a good way to suppress the event without duplicating functionality, adding conditional paths, etc.
fixes #2403
> regions plugin: disable "region-removed" event during plugin teardown

- CHANGES.md
- src/plugin/spectrogram/index.js
1. Remove inaccurate doubling of spectrogram (#2232)
2. Setting `splitChannels: true` going to draw spectrograms for each channels.
3ch spectrogram example
None.
None.
**This PR will change output of spectrogram.**
It seems like web browser resamples audio to fixed samplerate(in my case, 48kHz). #1248
So top of spectrogram frequency will be fixed regardless of original samplerate.
We can scale spectrogram, if there are nice way to get original samplerate(I couldn't find it).
#1248
fixes #2232
> spectrogram: Add multi-channel, Remove inaccurate doubling

- CHANGES.md
- src/drawer.multicanvas.js
This changes the way drawer renders bars. Prior to this, the height of each bar was [calculated only on the single peak at the start of bar, in `drawer.multicanvas.js:311`](https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.multicanvas.js#L311). This made the bars render almost randomly, especially at smaller widths, since highest peaks were very easily ignored, if not falling exactly where a bar started.
Here's an animated example of **before**, as you can see the original waveform is translated poorly, and then when resizing, bars jump around for no good reason:
Now instead, the height is [calculated on the whole range of peaks that each bar falls into](https://github.com/lorenzos/wavesurfer.js/commit/243a595a5c5684c44b06619d1aed4fe38fa93429#diff-9e1d85325663a8f99b981eac35 …
> fixed bars sizing using max peak value in range

- UPGRADE.md
- src/drawer.canvasentry.js
See: https://github.com/katspaugh/wavesurfer.js/pull/2437
> docs: add upgrade instructions for 6.0

- CHANGES.md
- src/drawer.multicanvas.js
Fixes #2439, an "unmasked" regression introduced with #2428. That regression broke bars rendering in the case a given pre-computed array of peaks alternates negative/positive values, instead of alternating positive/negative values (as wavesurfer itself generates).
> fixed bars rendering for peaks array starting with a negative value

- CHANGES.md
- src/plugin/regions/index.js
Changed the type of `maxRegions` from `number[]` to `number`.
> Correct type of maxRegions property of RegionsPlugin

- CHANGES.md
- src/plugin/timeline/index.js
when using negative values as `timeline.options.offset` the timeline is now rendered from start to the very end.  
before that change the timeline for those seconds of negative offset had not been rendered at the end of the waveform
fixes #2463
> timeline plugin: fix negative offset rendering

- CHANGES.md
- example/spectrogram/index.html
- src/plugin/spectrogram/index.js
Spectrogram plugin:
- Add `frequencyMin`, `frequencyMax` option to scale frequency axis.
- Set default 12kHz range to draw spectrogram like 5.x (#2455)
None.
None.
None.
#2424
fixes #2455
> spectrogram plugin: Add `frequencyMin`, `frequencyMax` scaling option

- docs/events.html
fixes #2475 
remove hint `Also fires on seeking.` of description of `audioprocess` event as it's not true during paused player
> [DOCUMENTATION] change description of audioprocess event

- CHANGES.md
- src/wavesurfer.js
Avoid unnecessary calculations when performing the responsive debounced resize check.
Background: In my app I use many simultaneous Wavesurfer instances and toggle showing/hiding different waveforms at different times. I noticed that on window resize each instance was firing `redraw` from the debounce function even if the waveform container was unpainted/had 0 width, leading to unneeded calculations. So I propose adding a check for a nonzero width value before incurring the expense of calling `redraw`.
This is a bit of a microoptimization that won't noticeably affect users with only a single Wavesurfer instance but for those using dozens or hundreds of instances the benefit compounds and this will reduce cpu use during resizes.
nothing
nothing
> responsive debounce optimizing: don't fire redraw if waveform is invisible

- CHANGES.md
- src/plugin/minimap/index.js
As soon as a new audio file starts to load the current minimap is cleared
fixes #2479
> minimap plugin: clear waveform when load new audio

- CHANGES.md
- example/spectrogram/app.js
- example/spectrogram/index.html
- src/plugin/spectrogram/index.js
**Title:** 
Spectrogram plugin: Fix for hi-dpi displays and independent height
- In Spectrogram plugin, fixed default rendering to have a consistent CSS height regardless of device pixel ratio.
- `height` can be provided as a configuration option to specify the display height independently from `fftSamples`. This allows you to choose a higher `fftSamples` value and show more detail on hi-dpi displays, and can also improve display quality when custom frequency ranges are selected.
- Labels respect device pixel ratio
- Frequency labels are now `fixed` instead of `absolute`, thus remaining visible when scrolling
None.
None.
fixes #2507
> Spectrogram plugin: Fix for hi-dpi displays and independent height

- docs/index.html
- plugins/index.html
Add basic documentation about using `wavesurfer.js` with NPM and CommonJS/ES6 modules 
nothing
nothing
nothing
https://github.com/katspaugh/wavesurfer.js/issues/1077
https://github.com/katspaugh/wavesurfer.js/issues/2427
> docs: brief notes on NPM/CommonJS/ES6 usage

- CHANGES.md
- src/plugin/regions/index.js
- src/wavesurfer.js
add `splitDragSelection` (default false) in `splitChannelsOptions` and check on it when splitting the drag selection
maybe update annotation example to include this
fixes #2529
refs #2380
> regions plugin: restore support for one drag selection for all channels

- CHANGES.md
- src/plugin/regions/region.js
With the use case that I use this library for, users need to be able to resize the regions. When a region was resized and afterward set back to the min length (f.e. 3.1 sec or in HMSM, which is how we show it, 00:00:03:10) it would stay at 3.12sec (00:00:03:12) or 3.14sec (00:00:03:14) or something, but never go back down all the way to 3.1 (00:00:03:10). With these changes, the length of the region can be set back to 3.10 exactly
> regions plugin: improved delta calculation (resize end)

- src/mediaelement.js
When using the MediaElement backend, it will be possible to subscribe to 'waiting' event.
This way, one can implement a loading indicator, showing it on 'waiting' and hiding it on 'canplay'.
> Proxy HTMLMediaElement's 'waiting' event through MediaElement backend.

- CHANGES.md
- src/util/silence-mode.js
fixes #2667 
adds a 1 second webaudio context buffer with 44100 bit rate to allow audio to play even if iphone silent switch is turned on.
preview here using latest wavesurfer.js version 6.4.0
https://www.entonbiba.com/lab/wavesurfer/2667.html
closes #2667
> Fix iphone silent switch webaudio mute

- docs/options.html
I hope that issue #1281 will be resolved in the future, making this option no longer useful.
> Add autoCenterImmediately option in the documentation

- .github/FUNDING.yml
Change the sponsorship account to the wavesurfer-js org.
> funding: update the sponsorship account

- src/plugin/markers/index.js
As a user, I would like to customize the font for labels that I add to markers. However, I am unable to assign a property from the top level component due to the specified font-family in the label element. 
```tsx
<Box
ref={waveformRef}
gap={2}
sx={{
maxWidth: '189px', // TODO: Can we not fix this?
display: 'flex',
alignItems: 'center',
span: {
color: theme.palette.primary.main,
marginTop: '-13px',
fontFamily: theme.typography.fontFamily,
}
}}
/>
```
This is my first PR in this repository! Please let me know if I missed something!
> Markers Plugin: Inherit `font-family` rather than setting `monospace`

- .github/workflows/publish.yml
- package.json
The release workflow is failing after migrating the repo to a new org.
> Fix: release workflow permissions

- README.md
There are quite a few video tutorials about wavesurfer.js on youtube.
I picked one from the first page that I think is very good. Kudos to the author!
> Docs: add a video tutorial link to the readme

- .github/workflows/publish.yml
- CHANGES.md
- bower.json
- package.json
Resolves #2723.
The release workflow intentionally fails when there's no new version to release, but this might look confusing because it looks like it failed due to an error.
Instead of `exit 1`, we're now checking for the new version on each step and exit w/o an error.
Also NPM publish actually wasn't working. @thijstriemstra as you noticed correctly in the dry-run, it was showing an error. Fixed it by adding a setup-node step.
> Fix: avoid exit 1 in CI script

- src/plugin/markers/index.js
Add a function to get all current markers to the wavesurfer object.
None I guess.
None I guess.
Untested.
I also would like to add it to the regions plugin if this is ok.
This way I dont need to keep track of the state outside of wavesurfer.
Great tool btw, using it for https://gitlab.com/fraggen/fraggen
> feat(MarkersPlugin):  add getMarkers function

- example/spectrogram/app.js
- example/spectrogram/index.html
- example/zoom/index.html
- example/zoom/main.js
- src/drawer.canvasentry.js
- src/drawer.js
- src/drawer.multicanvas.js
- src/plugin/spectrogram/index.js
- src/wavesurfer.js
As requested in #2741, a separate PR to revert "Zoom optimisation" (#2646).
Resolves #2738.
As @kai-shimada found out, v6.6.0 introduced a regression in width calculation. The only likely cause is https://github.com/wavesurfer-js/wavesurfer.js/pull/2646, so I suggest we revert it for now.
> Revert "Zoom optimisation"

- CHANGES.md
- bower.json
- package.json
This PR only updates package.json and the changelog on master. The release itself has already been [published](https://github.com/wavesurfer-js/wavesurfer.js/releases/tag/6.6.2) at an earlier snapshot of master w/o an unwanted commit that is currently on master (it will go live in another release).
> Release 6.6.2

- README.md
With the unpkg CDN, when the version is omitted, it will fetch the latest version published on NPM.
In our readme, we provide a CDN tag with the an unspecified version, as a way to keep users up-to-date.
However, if we release a major version update, e.g. 7.0.0, people who copied and pasted the unpkg tag from our readme, will have wavesurfer.js updated to that version, even though a major version update implies breaking changes.
Capping the version at `wavesurfer.js@6` would prevent users from unknowingly auto-upgrading with _intentional_ breaking changes.
Beaking changes or regressions can also occur _unintentionally_ (as was the case with 6.6.0), so pinning the minor version would be the safest (while still fetching bug fixes automatically).
The tag in the readme is obviously just a …
> Docs: version the unpkg script in readme

- src/plugin/markers/index.js
Markers plugin has a method called remove(idx) which removes one marker at index idx in the markers array in wavesurfer's markers object.
To remove a marker, we have to find the index of marker to remove by matching time, or label. This, I think can be improved because two markers can have same time and/or label.
Changes here introduce an id to each marker and a function removeById(id) which will find the index of marker with that id and call remove(idx)
related: see #2748
> Remove marker by id

- src/wavesurfer.js
> fix: relay dblclick event

- examples/custom-render.js
- index.html
- src/decoder.ts
- src/renderer.ts
- src/wavesurfer.ts
I've added a new option `renderFunction: (peaks, ctx) => void` which allows swapping out the default rendering function for a custom one.
Resolves https://github.com/katspaugh/wavesurfer.js/discussions/2811
> Feat: custom render function

- src/plugins/regions.ts
Hello First of all, thank you for making such a great library. While using the REGION PLUGIN you created, I needed a double click event handler, so I tried working on that pr. If I'm lacking or missing something, feel free to edit that pr or give me suggestions.
> Feature: add region plugin dblclicked event handler

- .github/workflows/publish.yml
- package.json
V6 releases should be published from the v6 branch, not master.
> V6: change the release branch and publish 6.6.4

- README.md
- src/wavesurfer.ts
We now provide a new time when emitting the `interaction` event. This provides consumers with realtime information about drag events. Before, consumers would need to wait for the debounce. Tested behavior locally.
Additional parameter to `interaction` event handlers, but should be non-breaking.
None
None
https://github.com/katspaugh/wavesurfer.js/issues/2844
> Provide a new time when emitting `interaction` events

- src/renderer.ts
If you set a height, the `.canvases` div (`canvasWrapper`) still ends up with `defaultHeight` (128px) because that is set prior to rendering. ie: the value returned from `getHeight()` is different when its set for `.canvases` and its child div.
I'm not sure if this is the best fix. Feels a bit hacky but I didn't have the time to look at it more closely. Figured I'd make the PR to give you a heads up. :)
> Fixes minHeight on `.canvases` div

- src/fetcher.ts
- src/player.ts
- src/plugins/record.ts
- src/wavesurfer.ts
This MR improves `RecordPlugin`:
- allows providing `mimeType` and `audioBitsPerSecond` params when creating a `MediaRecorder` instance;
- if `mimeType` was not provided, automatically detects currently supported type via `MediaRecorder.isTypeSupported()`;
- preserves recorded `mimeType` when loads audio for playback.
None
- `Player#.setSrc()` for its second optional parameter now  instead of `ArrayBuffer` expects `Blob`, which preserves original audio mimeType within itself.
None
Resolves #2836
> Check for supported mimeType in RecordPlugin

- src/wavesurfer.ts
Resolves #2895.
Duration can be already loaded when an existing audio element is passed, in which case there's no need to wait for the `loadedmetadata` event, it will never be fired.
> Fix: duration can be already loaded

- src/draggable.ts
- src/wavesurfer.ts
As suggested in #2890, since audio duration is polled on every tick, it would be beneficial to cache it until another audio file is loaded.
> Refactor: cache duration

- src/renderer.ts
Fixes #2807
The width was already x2 for high-DPI screens but not the height which resulted in slight distortions when using rounded bars.
> Fix: height x2

- src/renderer.ts
Resolves [#2845](https://github.com/katspaugh/wavesurfer.js/issues/2845)
A bug persists when barWidth or barGap is a floating number.
Todos/Notes:
requires e2e tests
Cheers!
> fix: narrow gaps between canvases

- src/renderer.ts
Allow the rest of the elements to be editable apart from the `cursor` element.
> All elements CSS editable 

- README.md
- package.json
- webpack.config.js
- webpack.config.plugins.js
Resolves #2903.
UMD files are now exported as `*.min.cjs` instead of `.min.js` for Node.js to recognize them as CommonJS modules.
> Fix: rename UMD files to .min.cjs

- package.json
Resolves #2877.
When module resolution in tsconfig is set to Node, it needs types explicitly exported by the package.
See https://www.typescriptlang.org/docs/handbook/esm-node.html
> Fix: export types for CJS modules

- README.md
- examples/vowels.js
- src/plugins/spectrogram.ts
Align the numeric and unit parts of Spectrogram labels a little bit better.
Originally, the unit font size was 10px and the numeric value size was 12px. Now they are both 12px and neatly aligned.
I've also updated the readme.
> Spectrogram: same font size for unit labels

- src/draggable.ts
- src/plugins/regions.ts
Resolves #2919.
Fixes drag selection in the Regions plugin when the container has a padding.
The draggable function now takes into account the container bbox's left and top in the onDragStart callback.
I also refactored and cleaned up the enableDragSelection function a bit.
Open the Regions example and drag on the waveform to create a region.
> Regions: fix enableDragSelection when container has padding

- README.md
Just adds a note in the README that the `barMinHeight` property is removed in v7. I went searching for how to achieve this in v7 and found the details in this [discussion](https://github.com/katspaugh/wavesurfer.js/discussions/2815).
> Add barMinHeight to list of removed options in v7

- src/player.ts
Resolves #2940
The media element's src needs to be cleared on destroy.
Destroy an already playing wavesurfer instance, observe that the sound should stop.
> Fix: reset media on destroy

- src/renderer.ts
Resolves #2945
The wrapper width needs to be reset to 100% in the beginning of a re-render so that it doesn't affect the width calculation.
This is only relevant in a `flex-grow: 1` container.
> Fix: reset wrapper width on re-render

- cypress/e2e/basic.cy.js
- cypress/e2e/options.cy.js
- cypress/e2e/regions.cy.js
- cypress/e2e/umd.cy.js
- cypress/e2e/umd.html
- package.json
- webpack.config.plugins.js
Resolves #2953
When importing a UMD module in Node.js, it's interpreted as a CommonJS module and should not assume any global variables.
So I've added a check to export into a global WaveSurfer object if it's available (browser), or export to the global `this` (Node.js).
> Fix: webpack config for plugins

- examples/regions.js
- src/plugins/regions.ts
Resolves #2946
Regions will now not resize when dragging past the edges of a waveform.
It can be tested on the updated Regions example by dragging the "fixed-size" region.
> Fix: [Regions] prevent resizing when moving over edge

- src/wavesurfer.ts
Resolves #2958
If a previous audio is playing when `load()` is called, pause it before starting to fetch a new one.
In the React example, press the Play button and then press Change audio.
> Fix: pause audio on load

- scripts/plugin.ts.template
- src/base-plugin.ts
- src/plugins/envelope.ts
- src/plugins/hover.ts
- src/plugins/minimap.ts
- src/plugins/record.ts
- src/plugins/regions.ts
- src/plugins/spectrogram.ts
- src/plugins/timeline.ts
- src/wavesurfer.ts
As pointed out by @nidhiwebsolutions [here](https://github.com/katspaugh/wavesurfer.js/discussions/2962#discussion-5363339), one might want to destroy a plugin while a wavesurfer instance is still intact. In this case, the plugin should be removed from the list of registered plugins.
Release Notes:
- New Feature: Introduced a new event type `destroy` in the `BasePluginEvents` type and emitted the `destroy` event when the `destroy()` method is called in the `BasePlugin` class.
- Bug fix: Modified the `destroy` method of the `SpectrogramPlugin` class to remove the plugin from the list of registered plugins before calling the superclass's `destroy` method.
- Refactor: Updated import statements and extended event types in various plugin classes to include `BasePluginEvents`.
> "Code changes …
> Fix: remove plugins on destroy

- .github/workflows/release.yml
- package.json
- tsconfig.json
Resolves #2969
Target ES6 instead of ES2021, so that it works on more platforms.
Syntax like this:
```js
this.wavesurfer?.load(this.recordedUrl)
```
will now be compiled to
```js
(_a = this.wavesurfer) === null || _a === void 0 ? void 0 : _a.load(this.recordedUrl);
```
This increases the minified bundle from 16 Kb to 17 Kb which is fine.
Release Notes:
- Chore: Updated the branch name for triggering releases from "beta" to "main" in the `.github/workflows/release.yml` configuration file.
> "From beta to main, a change so plain,
> A chore to update, with no code to gain.
> Branching strategy aligned, unintended consequences declined,
> Review this change, and peace of mind we'll find."
> Build: set compile target to ES6

- .github/workflows/ai-review.yml
- examples/all-options.js
- examples/predecoded.js
- src/renderer.ts
Resolves #2979
Older versions of Firefox didn't have `roundRect` so it should fall back to an unrounded rectangle.
> Fix: fall back to rect if roundRect is not supported (old FF)

- src/plugins/regions.ts
Resolves #2978
Regions can be zero-length, in which case they become markers, but this wasn't taken into account in the dragging restrictions which assumed a certain minimum length.
Drag one of the markers in the regions example.
> Fix: dragging zero-lengths regions (i.e. markers)

- src/draggable.ts
Resolves #2963
Right mouse clicks won't trigger dragging anymore.
> Fix: ignore right button clicks when dragging

- src/plugins/timeline.ts
Restores the timeline plugin formatTimeCallback function from v6.
copied over from v6
> timeline plugin: restores formatTimeCallback

- examples/fm-synth.js
- examples/record.js
- src/plugins/record.ts
Resolves #2971
The Record plugin will now re-use wavesurfer's rendering mechanism for the realtime waveform during recording.
> Fix: [Record] use all wavesufer options

- examples/_preview.js
- examples/regions.js
- index.html
- src/plugins/regions.ts
Resolves #2998
Resizing had a `start > 0` condition that should be `>=`.
Can be tested with the first region in the regions example.
> Fix: [Regions] resizing when start is 0

- examples/regions.js
- src/base-plugin.ts
- src/plugins/regions.ts
Resolves #2961
The Regions plugin now emits region-in and region-out events when a region is played over.
I've also fixed the event emitter type for plugins, it was too generic.
The Regions example now uses the new events for looping.
> Feat: [Regions] add region-in and region-out events

- package.json
- src/plugins/envelope.ts
Resolves #2995
The Envelope plugin now listens to media element volume changes and sets its GainNode volume to the same value.
This allows setting the audio volume via `wavesurfer.setVolume()` and not just `envelope.setVolume()`.
> Fix: [Envelope] react to media element volume changes

- .github/workflows/release.yml
- yarn.lock
Upgrade the minor versions of dev dependencies and migrate to another release action that doesn't display deprecation warnings.
> Chore: upgrade dev dependencies

- examples/all-options.js
- src/player.ts
- src/renderer.ts
- src/wavesurfer.ts
Resolves #3025
An internally created audio element is now added to the shadow DOM. If mediaControls is set, controls=true will be added to the element.
> Fix: restore mediaControls

- src/plugins/envelope.ts
Resolves #3032
Setting the volume to 0 resulted in a NaN value in `invertNaturalVolume`. It will now return 0 immediately.
> Fix: [Envelope] handle 0 volume

- examples/spectrogram.js
- src/plugins/spectrogram.ts
Resolves #3038
The Spectrogram plugin now takes a parameter to split the channels. If this option isn't specified, it will inherit it from the wavesurfer options.
> Feat: [Spectrogram] option to split channels

- package.json
- src/plugins/envelope.ts
Listening to audio element volume changes in the Envelope plugin breaks some use cases. Envelope volume should be set and controlled exclusively by Envelope. Users should call `envelope.setVolume()`.
> Fix: [Envelope] ignore audio volume changes (revert #3003)

- src/wavesurfer.ts
Resolves #3034
If an externally passed media element already has a duration when wavesurfer is initialized, the load function would return synchronously before any event listeners have a chance to subscribe to the ready event.
It's now always asynchronous even if duration is available synchronously. This makes the ready event emit _after_ event handlers are set.
> Fix: events in load should always be async

- src/plugins/hover.ts
- 0.4sec -> `0:00`
- 0.5sec -> `0:01`
- 0.9sec -> `0:01`
- 1.0sec -> `0:01`
- 1.4sec -> `0:01`
- 1.5sec -> `0:02`
- 0.4sec -> `0:00`
- 0.5sec -> `0:00`
- 0.9sec -> `0:00`
- 1.0sec -> `0:01`
- 1.4sec -> `0:01`
- 1.5sec -> `0:01`
Test with Timeline plugin by importing after modifying the package Hover plugin src code directly.
Sorry for an environment where I can't upload screenshots.
> Fix: [Hover] fix converting seconds method in formatTime

- src/decoder.ts
Resolves #3057
Resume AudioContext if it's suspended upon creation.
This might still not work in some browsers unless `load` is called on user action (e.g. on click).
> Fix: resume AudioContext if suspended

- examples/speed.js
- src/player.ts
Resolves #3058
Playback rate works unreliably if set before the audio has been sufficiently loaded.
This PR sets the initial playback rate when the `canplay` event is emitted on the media element.
> Fix: set initial playbackRate on canplay

- examples/record.js
- src/plugins/record.ts
Resolves #3017
This PR refactors and introduces breaking changes in the Record plugin API. It will be released in 7.1.0.
The Record plugin will now continuously monitor microphone audio and render a real-time waveform for it.
It can be stopped by calling the `stopMic()` method.
Events renamed:
* `startRecording` -> `record-start`
* `stopRecording` -> `record-end`
Recorded audio will *not* be rendered in the same wavesurfer instance anymore. Instead, the `record-end` event will return a blob that can be rendered in another wavesurfer instance.
> Feat: [Record] decouple real-time waveform and recorded audio

- README.md
- src/wavesurfer.ts
Resolves #3059
Restores the `wavesurfer.loadBlob` method from v6.
Allow passing a Blob directly instead of a URL.
> Fix: restore loadBlob

- examples/events.js
- index.html
- src/fetcher.ts
- src/wavesurfer.ts
Resolves #3056
This PR augments the fetcher with a reader that tracks the progress of a fetch request and adds a `loading` event.
A new example is added for testing all wavesurfer events.
> Feat: track the progress of fetch requests

- src/plugins/regions.ts
Resolves #3050
When calling `region.setOptions({ start: N })`, markers (regions w/o an end) could freeze because their end position wasn't updated.
It will now always sync the end position of a marker with its start position, unless an explicit new end position is passed.
Can be tested with this example: https://wavesurfer-js.org/examples/#b2eebd63f32ff5ef60d9b13aced55151
> Fix: [Regions] setOptions with markers

- package.json
~~TypeScript was complaining about not being able to find the declarations, so I fixed the exports map and tested it. Now I get full TS + autocompletion for plugin constructors.~~
This might've been an issue with VS Code misbehaving, so this PR is now just a bit of polish rather than a fix. I added a shorter way to import plugins, e.g.: `import SomePlugin from 'wavesurfer.js/plugins/some-plugin'`
> Chore: simplify plugin import syntax

- src/plugins/timeline.ts
If the timeline displays units other than seconds – such as beats, or video frame position – notch and label intervals are likely to be precise float when converted to seconds. Precision is especially important when zoomed in at a high minPxPerSec. 
Currently `primaryLabelInterval` and `secondaryLabelInterval` are specified in seconds, and the computation to assess whether a given notch position is a label rounds to 2 decimal places. This is presumably desirable in some cases but not in the aforementioned use case, where the loss of precision causes labels to be skipped altogether.
I'd therefore like to suggest an alternative way to specify when labels should occur, simply based on the number of notches. For example:
* `primaryLabelSpacing=10` means every 10th notch is a primary label.
* …
> Allow timeline label intervals to be specified in notch count as well as seconds

- src/plugins/regions.ts
- When regions are overlapped, region-out event triggered strangely
Previously, there was only one active Region.
However, if there are multiple regions, there can be multiple active regions.
I have improved the logic for this case.
- change activeRegion to actionRegions(array)
- find all played regions
- trigger event by  activeRegion & played regions
- update activeRegions
Check the triggered event(region-out) after overlapping different regions
```
//reg region
{
"listeners": {
"update-end": {},
"play": {},
"click": {},
"dblclick": {},
"remove": {}
},
"totalDuration": 103.944,
"minLength": 0,
"maxLength": null,
"id": "red",
"start": 26.9,
"end": 40.6,
"drag": true,
"resize": false,
"color": "rgba(242, 85, 75, 0.3)",
"element": null
}
// green region
{
"listeners": {
"update-end": {}, …
```
> Fix: [Regions] Overlpaeed Regions region-out event error

- src/wavesurfer.ts
Resolves #3097
The `pause` event isn't emitted as expected when the src is changed right after calling `pause()` which resulted in the timer being run after a new audio is loaded but not played yet.
I've added a new media event listener on `emptied` which is triggered when a new audio source is loaded.
> Fix: stop timer on "emptied"

- src/plugins/regions.ts
Resolves #3085
If a region is removed inside a region-created handler, it wouldn't be properly removed from the region list because other events haven't been subscribed to yet. I've moved the region-created call to the very end of the function to allow event listeners to be created before it.
> Fix: [Regions] fire region-created after subscribing to region events

- src/plugins/timeline.ts
Resolves #3070
Timeline's `container` option now accepts a CSS selector string along with an HTML element.
> Feat: [Timeline] accept CSS selector in the container param

- examples/all-options.js
- src/plugins/envelope.ts
- src/renderer.ts
- src/wavesurfer.ts
Envelope plugin:
* Add `getPoints`
* Allow giving points an id
Wavesurfer options:
* `dragToSeek` – dragging the playhead is now opt-in (a breaking API change ⚠️ )
> Feat: [Envelope] getOptions and point ids +  dragToSeek option

- examples/record.js
- src/plugins/record.ts
Resolves #3049
If `audioBitsPerSecond` isn't specified, the browser will record audio with a variable bit rate (VBR) which wavesurfer has trouble decoding. So I've added a default value for MediaRecorder's `audioBitsPerSecond` parameter which makes it record with a constant bit rate.
> Fix: [Record] a default value for constant bit rate

- cypress/e2e/regions.cy.js
- src/plugins/regions.ts
Resolves #3124
Allows setting region's content and id via `region.setOptions`.
E.g.
```js
region.setOptions({
id: 'new-id',
content: 'New content'
})
```
> Feat: [Regions] allow setting content and id

- src/renderer.ts
Resolves #3167
Use `getBoundingClientRect().width` instead of `clientWidth` to take CSS scaling into account.
> Fix: use bounding box for width calculation in dragToSeek

- README.md
Looks like the redirect from `https://wavesurfer-js.org/docs/methods` is no longer valid
Resolves #
> Update README.md with correct link to methods

- cypress/e2e/regions.cy.js
- src/plugins/regions.ts
Currently, adding a new region also creates left and right resize handles regardless of the resize param being set. For small regions, the resize handles makes it so you can't see the actual background color.
Add the resize param to the resize handle creation conditional.
```
regionsPlugin.addRegion({
...,
resize: false
});
```
Added an e2e test as well
Before: ![Before](https://github.com/katspaugh/wavesurfer.js/assets/32553602/f49887ff-7b8a-45f9-ac6c-b8b9202565f3)
After: ![After](https://github.com/katspaugh/wavesurfer.js/assets/32553602/90391291-7ba5-4e0f-aab0-2b685e12e221)
* [✅] This PR is covered by e2e tests
* [✅] It introduces no breaking API changes
> Regions plugin: Only add resize handles if resize prop is true

- src/renderer.ts
- src/wavesurfer.ts
Resolves #2655
I've added a double click event, and also added the Y mouse position to both click and dblclick.
It can be used like this:
```js
wavesurfer.on('dblclick, (x, y) => {
console.log('Double-clicked at %d, %d', x, y) 
})
```
Please note that any double click will also trigger a regular click. This can be worked around by setting `wavesurfer.options.interact` to false, which would disable regular clicks.
> Feat: add dblclick event

- cypress/e2e/index.html
- cypress/e2e/options.cy.js
- src/renderer.ts
Allows the user of the library to remount the wavesurfer instance to a new container.
Resolves #3197
This feature allows changing the container via setOptions and adds a new event type 'containerRemount' which is only emitted when the container is remounted i.e. updated via setOptions.
If only the container is updated, it wont try to rerender the waveform.
In the change we introduced a new file `equals.ts` which has common utility functions for comparing 
Perhaps the `equals.ts` needs it's own unit testing or to be changed to `lodash`'s utility functions but from my experience it has some quirkiness in some scenarios.
As usual you can test the via the `yarn test` command.
You can also test the feature via the new example `remounting-container.js`.
> Feat: update the container via setOptions

- cypress/e2e/basic.cy.js
- src/player.ts
Allow user to set `media` after creation of Wavesurfer instance.
Resolves #3190
Currently, we can specify a `media` element only during creation of Wavesurfer instance. In some advanced use cases where there are multiple players on a screen and we want to sync play/pause/seek between two players having the ability to share the `media` element during runtime would be advantageous, especially if one player is always persistent and survives screen navigation.
To enable this feature we added a public `setMediaElement` method to `Player` class.
As usual you can test with the `yarn cypress` command.
> Feat: add public method to set media element

- examples/webaudio.js
Use a `highshelf` filter instead of a `hishelf` filter, which does not exist.
Resolves #3225 
Uses a `highshelf` biquad filter node.
Run the example code.
> Use a `highshelf` filter in the web audio example

- cypress/e2e/basic.cy.js
- examples/react-global-player.js
- src/player.ts
- src/wavesurfer.ts
Media src shouldn't be reset if an external media element is passed in the options.
Also, I've made the exportPeaks algorythm the same as when rendering the waveform.
> Fix: keep external media on destroy

- README.md
I tried the documentation in the existing README and that was not picking up the types and VSCode complained:
```
Cannot find module 'wavesurfer.js/plugins/record.js' or its corresponding type declarations
```
I then chanced upon https://github.com/katspaugh/wavesurfer.js/issues/2877#issuecomment-1606044454 and tried that and everything worked correctly, with types picked up. This PR updates the documentation.
> Show the correct way to import with type definitions enabled

- examples/record.js
- src/plugins/record.ts
https://github.com/katspaugh/wavesurfer.js/discussions/3248
Adds pause/resume functionality to RecordPlugin so users can pause and resume the recording instead of only being able to start and stop the recording.
It uses [MediaRecorder.pause](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/pause) and [MediaRecorder.resume](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/resume)
The record.js example has been updated to include this functionality.
> feat: add pause/resume functionality to RecordPlugin

- examples/record.js
- src/plugins/record.ts
Resolves #3245
Open to feedback!
- Adds options to `startMic` and `startRecording` to use a specific mic (via deviceId)
- Add function to get a list of available audio devices `getAvailableAudioDevices`
1. Open the Record example. 
1. If you haven't allowed mic permissions on the site before, for this example you will need to hit the record button first, allow permissions and refresh the page for the list to be updated.
1. You should be able to select a mic from the list.
1. Hit record and test the mic.
In Chrome, you can reset the "Allow Mic" permissions by going to Settings > Privacy and Security > Site settings > Microphone > Click trash icon on `wavesurfer.xyz` or `localhost:9090`.
> Feat: Record Plugin - Choose Mic

- cypress/e2e/basic.cy.js
- src/player.ts
Resolves #3258
The `currentTime > 0` check was returning false at the beginning of playback, so I removed it.
> Fix: isPlaying() should return true directly after play()

- src/plugins/regions.ts
Resolves #3235
Calling `setOptions({ resize: true })` will now add resize handles if they weren't previously enabled. And vice versa, it will delete them if `resize: false` is set.
> [Regions] Fix: toggle resize handles in setOptions

- src/draggable.ts
- src/renderer.ts
Resolves #3257
`touch-action: none` on the scroll container was preventing scrolling on iOS.
It was added for `dragToSeek`, so I made it apply only when that option is enabled and dragging is performed.
> Fix: scroll zoomed waveform on iOS

- src/plugins/regions.ts
Resolves #3170
Region's start and end should not be below 0 and above audio duration.
> [Regions] Fix: clamp region start/end to audio bounds

- examples/record.js
Updates the Record example to use `RecordPlugin` instead of `record` to access the `getAvailableAudioDevices` function.
> Fix: [Record] Access `getAvailableAudioDevices` with `RecordPlugin`

- cypress/e2e/basic.cy.js
- src/player.ts
- src/wavesurfer.ts
When we change the underlying `media` element using `setMediaElement` the progress bar would not update as the track was playing. This was because of various media events subscriptions was missing. 
Resolves #3266
To ensure that we are properly handling setting of a new media element `setMediaElement` has been tweaked as follows:
1. Unsubscribe from all event listeners for current `media` element
2. Attach the new `media` element
3. Subscribe to media (player) events for newly attached `media`
1. Create a Wavesurfer instance
2. Attached another `media` element using `setMediaElement`
3. Play
The progress bar should be updated as the track play progresses.
> Fix: setMediaElement to properly subscribe/unsubscribe media events

- examples/zoom-plugin.js
- index.html
- src/plugins/zoom.ts
Add zoom plugin  ,which implements waveform zoom operation via mouse wheel.
By calculating the scaled ratio and scroll position based on the audio time at the mouse's location, the current zoom level, and the width of the div container, we can then adjust the zoom level of wavesurfer and control scrolling
> feat add ZoomPlugin

- README.md
- cypress/e2e/basic.cy.js
- cypress/e2e/options.cy.js
- examples/basic.js
- examples/zoom-plugin.js
- src/event-emitter.ts
- src/wavesurfer.ts
- src/webaudio.ts
Resolves #3272
I've restored the `backend: 'WebAudio'` option.
There's a new class WebAudioPlayer that can be used as a drop-in replacement for a HTMLMediaElement. It emulates an audio element via a Web Audio buffer source node.
> Feat: restore the "backend: 'WebAudio'" option

- src/renderer.ts
Resolves #3270
The main waveform is now clipped so that it doesn't bleed through behind the progress waveform.
> Fix: avoid color bleed behind progress canvas

- src/plugins/record.ts
You can now use a real-time MediaStream object to generate waves with Record plugin
Example get stream by tag audio
> set public renderMicStream of Record plugin

- examples/record.js
- src/plugins/record.ts
Adds an option to the Record plugin to render a streaming waveform while recording. Limited to a given window of time (default 5s).
Adds two options to the plugin config when calling `RecordPlugin.create()`
```ts
/** Whether to render the scrolling waveform, true by default */
scrollingWaveform?: boolean
/** The duration of the scrolling waveform window, defaults to 5 seconds */
scrollingWaveformWindow?: number
```
Left unset, the plugin works the same as before.
Also
- FIXED: stop while in paused state, works as expected
- FEAT: pausing the recording, pauses the wave display 
Note: This is my first contribution to this repo, so I'm not too sure of the protocol. If this is something you want to edit, give a bit of time, or ditch - I won't be offended 👍
Demo here …
> Feat: Record plugin - streaming waveform animation

- src/fetcher.ts
- src/plugins/record.ts
Resolves https://github.com/katspaugh/wavesurfer.js/discussions/3313
We clone the fetch response to track loading progress, so errors need to be caught for both the main fetch promise and the progress reader.
> Fix: uncaught error in fetch progress reader

- cypress/e2e/options.cy.js
- src/plugins/minimap.ts
- src/wavesurfer.ts
Resolves #3324
The `load` method will not attempt to fetch an empty URL. It will just render a predecoded waveform if peaks and duration are provided.
> Fix: allow loading an empty URL string with peaks

- src/plugins/timeline.ts
Resolves #3314
If audio duration is known from the start, render the Timeline immediately.
> Fix: [Timeline] render on initial redraw

- src/wavesurfer.ts
Resolves #
Changed how initial re-rendering is handled. Previously, this wasn't wrapped with requestAnimationFrame and that's why the global waveform was laggy on the first play (it was perfectly fine when pausing and resuming)
Go to [example](https://wavesurfer.xyz/examples/?react-global-player.js) and try to play 2nd track. The row waveform will be playing perfectly, the global one will lag. Try to run this PR locally and you'll see that this lag is gone now due to requestAnimationFrame.
> Fix timeupdate render to use requestAnimationFrame

- src/plugins/regions.ts
Resolves #3300
The content size is now calculated for the text bounding box, not the entire region.
> Fix: [Regions] improve overlapping content

- examples/regions.js
- src/plugins/regions.ts
Resolves #3328
Markers' `end` position is equal to the `start` position, so the current region detection wasn't working.
> Fix: [Regions] region-in/out event for markers

- src/plugins/record.ts
Resolves #3304
Wavesurfer options are now restored when the Record plugin is destroyed.
> Fix: [Record] restore interact and cursor width on destoy

- src/plugins/minimap.ts
Makes the minimap option `container` optional.
In the options passed to `MinimapPlugin.create()`, the `container` option is optional. However, the typing has it set as required. Not including it resulted in the TypeScript error `TS2345: Argument of type {} is not assignable to parameter of type MinimapPluginOptions. Property container is missing in type {} but required in type WaveSurferOptions.` This PR removes that error since the option is not required, and in fact, the minimap code handles the case where `container` is undefined.
The previous workaround was to coerce the typing: `MinimapPlugin.create({} as MinimapPluginOptions)`
> Type minimap container as optional

- examples/zoom-plugin.js
- src/plugins/zoom.ts
This makes changes to `ZoomPlugin`, which was added in #3276. Each change is on its own commit on this branch, to make reversions/modifications easier if requested before approval.
The zoom is currently triggered by the wheel event. On a trackpad, horizontal scrolling fires a wheel event with both an X- and Y- delta, unless the user scrolls perfectly horizontally on the trackpad, which is not typical. This creates a poor UX when the user is attempting to scroll because the waveform errantly zooms simultaneously. This PR changes the event listener to perform a zoom only when the Y-delta is greater than the X-delta, which is the case for the pinch gesture.
Currently the zoom level is adjusted by the same amount for each wheel event that is fired. This PR changes the event listener to adjust …
> Zoom plugin improvements

- src/renderer.ts
renderer: covertColorValues vertical color gradient is misaligned when devicePixelRatio is not 1
Resolves #3390
In renderer.ts `convertColorValues`
```
const gradientHeight = canvasElement.height * (window.devicePixelRatio || 1)
const gradient = ctx.createLinearGradient(0, 0, 0, gradientHeight)
```
Add a color gradient array. Check on desktop and then on mobile. Gradient on mobile is misaligned before fix. Post fix, it will align on different screens as expected.
> fixes 3390 covertColorValues vertical color gradient is misaligned when devicePixelRatio is not 1

- src/plugins/timeline.ts
We wanted a way to have all time indicators & ticks presented with equal visual prominence.
Added a new option, `secondaryLabelOpacity`, which defaults to 0.25.
Opening this in draft state so we can discuss. Open to any feedback/changes!
> Feat: [Timeline] Can now specify secondary label opacity

- src/plugins/timeline.ts
The current timeline plugin creates elements with `div[part=timeline-notch]`.  There are currently three different types of timeline notches: primary, secondary, and unlabeled tickmarks.  This PR appends one of the following to each notch element part:
* `timeline-notch-primary`
* `timeline-notch-seconary`
* `timeline-notch-tick`
Resolves #
Updated `plugins/timeline.ts` to set the `part` attribute.
Inspect the timeline `div` tags in the examples section. All notch elements should contain one of the following:
- `part="timeline-notch timeline-notch-primary"`
- `part="timeline-notch timeline-notch-secondary"`
- `part="timeline-notch timeline-notch-tick"`
> Feat: Add timeline-notch-{mode} to part

- cypress/e2e/options.cy.js
- src/renderer.ts
- src/wavesurfer.ts
Resolves #3400 and #3395.
Height in `splitChannels` is now taken into account when rendering individual channels.
> Fix: splitChannels height

- src/plugins/zoom.ts
Zooming with a trackpad was causing huge CPU spikes due to constant redraws. This PR imposes rate limiting via a delta threshold before actually redrawing the waveform.
Debounce & throttle were not appropriate here, as we don't necessarily want to throttle the events, we just want to ignore the "in-between" delta values and have a more notched zoom (a la Adobe Audition).
Test using any trackpad with smooth scrolling (i.e. lots of event firing when scrolling).
* [?] It introduces no breaking API changes
> Fix: [Zoom] Performance improvements (especially w/ trackpad zoom)

- examples/zoom.js
- src/plugins/record.ts
- src/renderer.ts
Resolves #3384
Drag-to-seek will now scroll the waveform when dragging close to the edge.
> Fix: scroll when dragging

- src/plugins/regions.ts
Add `region-removed` event to `RegionPluginEvents`, which emits when a Region's `remove` event is dispatched.
Resolves #
This `region-removed` event fires after the Region has been removed and is not cancelable.
> Feat: [Region] Add region-removed event

- README.md
- src/plugins/regions.ts
Resolves #3381
When dragging a region, the cursor should change to `grabbing` immediately on click.
> Fix: [Regions] grabbing cursor on mousedown

- src/plugins/regions.ts
Resolves #3244
When a region is dragged past the edge of a scrollable container, scroll the container accordingly.
> Feat: [Regions] scroll container when dragging a region

- src/player.ts
Resolves #3435
Calling load isn't necessary. The browser will now decide whether to load audio or not based on the `preload` property of the audio element which wavesurfer doesn't explicitly set. So it should likely default to `metadata` as per the [docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#preload).
> Fix: rm force-loading of audio

- src/draggable.ts
- src/plugins/regions.ts
Resolves #3428
`enableDragSelection` now takes a fourth optional parameter – a sensitivity threshold (defaults to 3px). It translates to how far one should move the mouse before a dragging event kicks in. Everything below the threshold is considered just a click.
> Feat: [Regions] pass sensitivity threshold to enableDragSelection

- src/plugins/spectrogram.ts
Resolves #3337
I've added a check for decoded data. If no data is available yet, the render method will fail silently.
I've also marked render and most other methods of the plugin as private. The only public ones are `destroy` and `loadFrequencyData(url)`.
> Fix: [Spectrogram] check for decoded data in render

- package.json
- rollup.config.js
- src/base-plugin.ts
- src/event-emitter.ts
- src/wavesurfer.ts
- src/webaudio.ts
- yarn.lock
I've cleaned up the public API a bit, and restored the combined types in `types.d.ts` which were reverted in #3450.
* Removed `addEventListener` and `removeEventListener`. Only `on` and `un` should be used in the public API.
* Renamed `BasePlugin.init` to `BasePlugin._init` to discourage calling it directly, as it's an internal method that has to remain public.
* `WebAudioPlayer.getChannelData` – needed by the Multitrack plugin.
* `dist/types.d.ts` – all core wavesurfer types in one module
> Refactor: rollup all types into a separate types.d.ts file

- src/renderer.ts
Resolves #3465 and #3460
A resize observer on the scroll container could cause an undesired re-rendering of the waveform when the height of the container changes.
> Fix: limit resize observer to width

- src/player.ts
- src/webaudio.ts
Resolves #3380 
As per [this comment](https://github.com/katspaugh/wavesurfer.js/discussions/3380#discussioncomment-8034069), if an audio file is fetched from a server that doesn't send the correct MIME type, the downloaded blob might fail to play in an audio element.
I've added a check when setting an audio src to a blob URL: if the MIME type is not supported, it will fallback to the original audio URL.
> Fix: don't use a blob URL for unknown MIME types

- src/draggable.ts
- src/plugins/envelope.ts
Resolves #3476
In draggable.js, the pointerout and pointercancel events will now be handled only when fired on the document object and not on inner elements. This allows dragging past the container until the mouse is completely outside of the page.
This PR also fixes a bug in the Envelope plugin where newly added points were not rendered correctly.
> Fix: draggable pointerout only on document

- src/renderer.ts
- src/wavesurfer.ts
Currently the `redraw` event firers before `renderHead` and `renderTail` have completed. This adds a new event `redrawcomplete` that fires once both head and tail have completed rendering.
In longer files `redrawcomplete` can take awhile to fire so we left `redraw` and `redrawcomplete` as two separate events
Resolves #
1. Navigate to [zoom example](http://127.0.0.1:9090/#zoom-plugin.js)
2. Add: `['zoom', 'redraw', 'redrawcomplete'].forEach((e) => wavesurfer.on(e, () => console.log(Date.now(), e)))`
3. view console
> Feat: add redrawcomplete event

- cypress/e2e/basic.cy.js
- examples/events.js
- src/renderer.ts
As outlined [in a comment](https://github.com/katspaugh/wavesurfer.js/pull/3480/files#r1447869479) in #3480, I've refactored the code that was awaiting all waveform chunks to be rendered into sequenced promises.
The rendering timeouts are now also promise-based, and it a render timeout is cancelled due to another rendering (e.g. when zooming using a slider), it will also reject the correspondng promise. So it's possible to track the entire chain of promises to determine where `rendercomplete` should be called.
@brian-byassee @jason-whitted please review
> Refactor: promise-based chunked rendering

- src/plugins/regions.ts
Resolves #3494
Pass the `side` variable to the update event. We only call `adjustScroll` when it is the region being dragged.
Use [localhost regions example](http://127.0.0.1:9090/#regions.js)
See that `adjustScroll` only fires for region drag events
*IMPORTANT NOTE: this stops a broken experience but it fails to fully implement what a user would expect to happen when resizing/dragging a region with a scrollbar.
> Fix: Region update event

- src/plugins/regions.ts
Make toggleCursor in regions.js safe.
Resolves #
It is possible for toggleCursor to be called but the element has been removed. This makes that event safe.
> Fix: make toggleCursor in regions.js safe

- src/player.ts
- src/renderer.ts
- src/wavesurfer.ts
Resolves #3298
If no audio is loaded but a waveform is rendered using pre-decoded peaks and duration, clicking on the waveform will now set the cursor to that position.
> Feat: support seeking with no audio loaded

- src/plugins/timeline.ts
- src/renderer.ts
Add part attributes to the other remaining elements rendered in the wavesurfer
Resolves #
Makes writing css easier outside the shadow root
- timeline
- canvases
- canvas 
- canvas-wave
- canvas-progress
- canvas-container
- progress-container
> Feat: add part attribute to timeline

- src/renderer.ts
Fixes memory leak that is caused by calling `draw()` in an infinite loop
Check if `viewportLen` is greater than 0 before drawing (and adding canvases).
Without this check, the tail cycle will run infinitely, because `i += viewportLen` will never change the `i` value.
https://codesandbox.io/p/sandbox/fancy-lake-vddsjh
Inspect the DOM and see how many canvases are being added
> Do not render the waveform if viewport is 0

- src/renderer.ts
The playhead position can drift a lot during zoom operations. Especially when zooming out when the playhead is at the end. 
This PR improves the accuracy of the offset needed to `scrollLeft` to keep the playhead visible. It does this by adding 1/2 pixel values to the `scrollLeft`
(1/2 pixels is the level of precision supported with scrollbars)
Resolves #
Limits issue where playhead ends up off screen durning zoom operations.
Using the [Basic Zoom](http://127.0.0.1:9090/#zoom.js)
Zoom out and set play head towards the end.
Zoom in to the play head
Then zoom out.
Note that the playhead is immediately lost on zoom out
With updates
https://github.com/katspaugh/wavesurfer.js/assets/47955954/f5ab9031-c080-45ab-995c-1a0ff3b5bf7c
Without updates …
> Feat: Improve scroll position adjustments on zoom in/out

- package.json
Resolves https://github.com/katspaugh/wavesurfer.js/discussions/3531 (sorry, I guess I should've made this an issue but I thought maybe I was just messing something up)
Type defs weren't working for imported plugins in a Next.js project.
- `bun create next-app`
- `bun add @wavesurfer/react wavesurfer.js`
```tsx
// app/page.tsx
'use client'
import React, { useRef, useEffect } from 'react';
import { useWavesurfer } from '@wavesurfer/react';
import RegionsPlugin from 'wavesurfer.js/dist/plugins/regions.esm.js'; // This import throws a type def warning usually
export default function Page() {
const containerRef = useRef<HTMLDivElement>(null);
const { wavesurfer } = useWavesurfer({
container: containerRef,
waveColor: 'violet',
progressColor: 'purple',
backend: 'MediaElement',
});
useEffect(() …
```
> Chore: Update plugin exports in package.json

- cypress/e2e/basic.cy.js
- src/player.ts
- src/renderer.ts
- src/wavesurfer.ts
This adds a `setScrollTime` method to `wavesurfer` that takes a time in seconds. It also adds `setScroll` and `setScrollPercentage` methods to `renderer` which are used by `setScrollTime`.
This allows the viwing window to be set indepenently of the play head.
Resolves: https://github.com/katspaugh/wavesurfer.js/issues/3411
Related: https://github.com/katspaugh/wavesurfer.js/discussions/3361
`setScrollTime` uses the current duration to calculate the percentage within the file. It forwards that percentage to `setScrollPercentage` in the `renderer`, which then uses the width of the scroll container to calculate an exact offset to pass to `setScroll`.
```
yarn cypress
```
> Feat: Add setScrollTime method

- src/draggable.ts
- src/renderer.ts
- src/wavesurfer.ts
Add dragstart and dragend events for drag to seek feature.
Resolves #
Add two new events and updated the functions passed to makeDraggable to make start and end emit the new event
http://127.0.0.1:9090/#all-options.js
Add
```js
wavesurfer.on('drag', (x) => console.log('drag',x))
wavesurfer.on('dragstart', (x) => console.log('dragstart',x))
wavesurfer.on('dragend', (x) => console.log('dragend',x))
```
check box to make Drag to Seek active.
Observe console.
> Feat: dragstart and dragend events for drag to seek

- src/player.ts
- src/wavesurfer.ts
- src/webaudio.ts
Resolves #3575
Two fixes for the WebAudioPlayer:
* The `seeking` event is now emitted _after_ `currentTime` is set to a new value
* Allow starting a playback without an src
* Pass a custom pre-calculated duration if audio src is not set
This effectively allows visually "playing" pre-decoded peaks and duration without an audio URL using the WebAudioPlayer.
> Fix: allow "playing" WebAudioPlayer w/o a URL

- cypress/e2e/error.cy.js
- src/wavesurfer.ts
Adds support for `wavesurfer.on('error')` event. This is helpful when building components where the file source is unknown at build time and you might want to hook into that event to display an error message.
It catches errors thrown by "Fetcher.fetchBlob" and emits it as an event named `error`
```
yarn test -- --spec ./cypress/e2e/error.cy.js
```
I think it's likely that this introduces a breaking API change if users previously relied on `.create` throwing an exception which is now caught and reported by `.on('error')`.
> Feat: add error event

- cypress/e2e/error.cy.js
- src/player.ts
- src/wavesurfer.ts
A follow-up on #3532.
* The error event handler now takes an Error object
* Async fetching/decoding errors in the constructor are now caught and emitted as an `error` event.
* Calling `load` and `loadBlob` will still result in a rejected promise on error (it was swallowed in the original PR), while also emitting an `error` event.
* Remove a breaking blob check.
> Refactor: re-throw error on load

- src/renderer.ts
- src/wavesurfer.ts
> add dragDebounceTime as an option

- cypress/e2e/regions-no-audio.cy.js
- src/wavesurfer.ts
This makes it so that the regions plugin will fire `region-in` and `region-out` events when audio is not loaded into wavesurfer.
Resolves #3570
This just fires a `timeupdate` event in the `setTime` method. This was the smallest change I could make to get the regions plugin to fire events.
If there's a better way to make this happen I'd love to hear some suggestions.
Use pre-decoded `peaks` and a `duration` to render a wavesurfer with no audio loaded. Add the regions plugin, and add a region. Add a `region-in` handler to the regions plugin, and then call `wavesurfer.setTime()` with a value inside the region. The handler for the `region-in` event should fire.
N/A
> Emit `timeupdate` when calling `setTime`

- src/draggable.ts
- src/renderer.ts
Resolves #3613
Adds a delay before triggering a drag gesture on mobile.
I've refactored and optimized the makeDraggable function, and added a touch delay option to prevent accidental dragging on mobile.
> Fix: draggable touch delay

- src/plugins/minimap.ts
Resolves #3566
The Minimap plugin will now attempt to initialize on creation. If the audio isn't decoded yet, it will initialize on ready.
> Fix: init minimap immediately

- src/plugins/timeline.ts
Resolves #3551
The timeline wrapper had a 0 height when, resulting in an overlap with the waveform.
> Fix: timeline height

- src/plugins/envelope.ts
- src/plugins/regions.ts
- src/renderer.ts
`makeDraggable` has memory leak in `renderer` and `plugins`(envelope and regions)
Using subscriptions to collect the return function of `makeDraggable` and unsubscribe it when destroyed or moved.
1. git clone https://github.com/wfk007/test-wavesurfer
2. pnpm install
3. pnpm run dev
4. visit http://localhost:8000/docs
5. open performance in devtools
6. GC manually and start a new record
7. toggle between `Docs` and `test dragToSeek option` many times
8. stopped at `Docs` page, GC manually and stop the record
before
after
> Fix: makeDraggable memory leak

- src/plugins/hover.ts
Add `formatTimeCallback` option for Hover plugin
Reuse previous `formatTime` method as a new option named `formatTimeCallback`.
- yarn start
- Go to Hover plugin's page on the app
- Hover the waveform to see plugin's working
- In Hover.create object in params, add 
```
formatTimeCallback(time) {
const hours = Math.floor(time / 3600);
const minutes = Math.floor((time % 3600) / 60);
const seconds = Math.floor(time % 60);
const formattedTime = [hours, minutes, seconds]
.map(value => (value < 10 ? `0${value}` : value))
.join(':');
return formattedTime;
},
```
- Hover the waveform to see time label as "hh:mm:ss"
> feat(hover): add formattimecallback option

- src/wavesurfer.ts
fix: https://github.com/katspaugh/wavesurfer.js/issues/3637
1. move `new AbortController()` from `constructor` to `loadAudio`
2. add compatibility check for `AbortController`
refer to: https://github.com/katspaugh/wavesurfer.js/issues/3637
> Fix: DOMException in destroy

- src/draggable.ts
This reverts commit 74308ba5bcfa6a53d3f01952b67f75a07cb9ae15.
Resolves #3642
> Revert "Fix: draggable touch delay (#3616)"

- src/renderer.ts
- src/wavesurfer.ts
Resolves #3659
I didn't check pixels in `setScroll` because it's redundant, setting invalid value for scrollLeft will be set as left or right edge.
> update: expose setScroll api from render

- src/renderer.ts
Resolves #3682
Please see #3682
Please see #3682
Please see #3682
> fix: when width is set high, now multiple canvases are rendered

- src/renderer.ts
Resolves #3687 
https://github.com/katspaugh/wavesurfer.js/assets/15643533/242e0636-3fe4-4f73-92a0-df55dada7a8a
> Fix `y` position in `click` and `dbclick` events

- src/wavesurfer.ts
Resolves #3691
I've copy-and-pasted @ajrisi's fix for the sample window. See https://github.com/katspaugh/wavesurfer.js/issues/3691#issuecomment-2102951061
> Fix: exportPeaks accumulating a precision error

- src/renderer.ts
The width of individual canvases wasn't calculated correctly in some edge cases. This resulted in the rendering crashing with very long audio files.
Can be tested by changing minPxPerSec to 70 in this example: https://wavesurfer.xyz/examples/?d5da9feca7995cd70caabe1ce6ec18d4
> Fix: clamp max canvas width

- src/plugins/regions.ts
Region overlap detection works incorrectly when regions are created successively. They need to wait for each other to correcrly check for an overlap. So I've added a small timeout.
> Fix: [Region] regions overlap detection with a delay

- src/renderer.ts
Resolves #3696
Instead of rendering the entire waveform asynchronously chunk by chunk, render only the chunks that are in the viewport.
We subscribe to the `scroll` event and render the parts of the waveform that are currently visible. If the number of canvases exceeds 100, we clear the old canvases.
It can be tested with this example: https://wavesurfer.xyz/examples/?d5da9feca7995cd70caabe1ce6ec18d4
The `redrawcomplete` event was previously emitted when all canvases finish rendering. Now it will be emitted after the initial 2 canvases are rendered.
> Feat: render canvases on scroll

- cypress/e2e/abort.cy.js
add two test cases for abort, refer to: https://github.com/katspaugh/wavesurfer.js/pull/3641#issuecomment-2041978173
case1: destroy before wavesurfer ready should emit AbortError Exception, it is for https://github.com/katspaugh/wavesurfer.js/pull/3614
case2: load url after destroyed should not emit AbortError Exception, it is for https://github.com/katspaugh/wavesurfer.js/issues/3637
yarn run cypress
> docs: add test cases for abort and destroy

- src/renderer.ts
Resolves https://github.com/katspaugh/wavesurfer.js/discussions/3690
Alter getHeight function to divide the parentHeight by number of channels if the height=auto of the wavesurfer instance
- Give the parent container a height
- Set `height : auto` & `splitChannel : []` of Wavesurfer instance
- Observe the waveforms not overflowing outside the parent container as their heights are 
splitChannel=[] | splitChannel=undefined
--- | ---
> Fix: Split channel overflowing when height:auto

- cypress/e2e/regions.cy.js
- src/plugins/regions.ts
- src/plugins/timeline.ts
- src/renderer.ts
- src/wavesurfer.ts
Requested in #3696
A region's element will be now rendered only if the region is in view.
> Refactor: [Regions] virtualize DOM elements

- src/renderer.ts
Resolves #3732
ResizeObserver isn't available in older browsers.
> Fix: check if ResizeObserver is defined (Safari 12)

- src/player.ts
Resolves #3733
If setting a blob URL fails, fall back to the original URL.
> Fix: add try-catch for src setting

- src/plugins/timeline.ts
In this PR, the width used to calculate `pxPerSec` in TimelinePlugin is retrieved from the `scrollWidth` of the Wavesurfer wrapper, for cases where the timeline wrapper itself is not a child of the wavesurfer wrapper. This enables timelines and waveform to stay visually in sync when zooming.
Resolves #3742
Used `this.wavesurfer.getWrapper()` to access the `scrollWidth` property when possible, otherwise default to `this.timelineWrapper.scrollWidth`.
1. Create a Wavesurfer instance, with e.g. "#waveform" as a container
2. Create a TimelinePlugin instance, with e.g. "#timeline" as a container
3. Call .zoom(zoomLevel) on the Wavesurfer instance to change the zoom level of the waveform
=> The timeline will rerender properly and follow the current zoom level of the waveform
```
import …
```
> Fix: Retrieve scrollWidth from Wavesurfer wrapper in TimelinePlugin

- src/renderer.ts
Related to #3696
With a very wide and zoomed in waveform, there could be gaps in the rendering.
> Fix: prevent gaps in zoomed in waveform

- src/plugins/timeline.ts
- src/renderer.ts
- src/wavesurfer.ts
Reported in https://github.com/katspaugh/wavesurfer.js/issues/3696
The virtual rendering in Timeline was doing too many DOM operations on each scroll, making the playback choppy. I've made it append and remove nodes only when their visibility changes.
> Refactor: optimize Timeline virtual rendering

- package.json
- scripts/clean.cjs
The `build` npm script currently fails on non-unix platforms where `rm` is not defined. This PR makes the script cross-platform.
Resolves #3746
1. Created a `scripts/clean.cjs` script to recursively delete `dist` folder using nodejs APIs
2. Added a `clean` npm script which calls `scripts/clean.cjs`
3. Call `npm run clean` instead of `rm -rf dist` in `build` npm script
Run `yarn build`. Any existing `dist` folder should be removed and the build process should execute correctly.
> Make yarn build command cross-platform

- src/plugins/record.ts
On Safari on both Mac and iOs, the audio generated by the record plugin cannot be properly processed by the OpenAI whisper model. This is a known issue that is addressed by passing a timeslice param of 1000 to the mediaRecorder.start() call.
If the optional `mediaRecorderTimeslice` value is provided to the RecordPlugin initializer, the value is passed to the `mediaRecorder.start()` call.
Pass a value of 1000 when running on any browser on iOS or in Safari on MacOS, recorded audio will be processed by OpenAI whisper. Without this value, only the first second or so of audio is correctly processed.
N/A
> Add mediaRecorderTimeslice option to RecordPluginOptions

- cypress/e2e/basic.cy.js
- src/wavesurfer.ts
Resolves #3744
When both peaks and duration were passes as options, onReady subscriptions weren't firing because the load was happening synchronously. With this PR, duration is always a promise.
> Fix: async duration to allow ready event subscriptions

- examples/basic.js
- src/renderer.ts
Resolves #3771
* devicePixelRatio < 1 resulted in waveforms not filling the container
* With devicePixelRatio = 2, waveforms w/o scroll were 2x wide
> Fix: handle devicePixelRatio < 1

- README.md
- src/plugins/regions.ts
This should fix the docs generation at https://wavesurfer.xyz/docs/types/plugins_regions.Region
> Fix: [Regions] export Region class for TypeScript docs

- examples/regions.js
- src/plugins/regions.ts
Resolves #3779
A new Regions event is added:
```
/** When a region is being updated */
'region-update': [region: Region, side?: 'start' | 'end']
```
```js
import WaveSurfer from 'wavesurfer.js'
import RegionsPlugin from 'wavesurfer.js/dist/plugins/regions.esm.js'
// Initialize the Regions plugin
const regions = RegionsPlugin.create()
// Create an instance of WaveSurfer
const wavesurfer = WaveSurfer.create({
container: '#waveform',
url: '/examples/audio/audio.wav',
plugins: [regions],
})
regions.on('region-update', (region, side) => {
console.log('A region is being dragged or resized', region)
})
```
> Feat: [Regions] emit region-update event

- src/plugins/record.ts
`requestAnimationFrame` has a different delay depending on the screen's FPS, so it results in a different continuous waveform speed. Changing it to `setTimeout` gives a more predictable result.
I've also optimized the performance of the `continuousWaveform` rendering:
* The smallest FFT size (32) because we only need one value per frame
* Math.max -> a loop
> fix: (Record) setTimeout instead of requestAnimationFrame

- src/plugins/minimap.ts
Added most of the wavesurfer events (skipped the ones that seemed redundant) to the minimap
Relays the miniWavesurfer events to the plugin. Added description of each events for the docs
> feature: [Minimap] more subscribable events

- package.json
- rollup.config.js
- yarn.lock
Resolves #3851
Introduce glob as a dev dependency and modify the rollup typescript bundling configuration.
> deps: add glob as dev dpes

- package.json
- src/renderer.ts
- src/wavesurfer.ts
Resolves #3602
I've added the nonce property as a new parameter in the WaveSurferOptions type. In the renderer.ts it checks if it was passed, and if it was, it adds it to the style being injected. This assumes you have the nonce value in your frontend to be able to be passed as a option.
Try adding a valid nonce value to your WaveSurfer element like this: {nonce: 'example-value'}
> Fix: adding nonce as a option in wavesurfer parameters to solve CSP problems

- src/plugins/regions.ts
Added parentElement check in virtualAppend method to prevent redundant DOM operations that were breaking click event handling during zoomed playback.
Resolves #3911
Resolves #3804
This PR resolves two related issues with region-clicked events and seeking inside regions in WaveSurfer.js:
1. **Issue #3911:**  
The `region-clicked` event was not firing on Chrome and Safari when the zoom slider was used. This behavior was inconsistent across browsers, as Firefox worked as expected.
2. **Issue #3804:**  
Since version 7.8.2, clicking inside a region no longer seeks the audio position correctly on Chrome and Edge. The expected behavior (as seen in Firefox) is that clicking inside a region seeks the audio to the clicked position.
Modified regions.ts virtualAppend method to check element's DOM …
> Fix: region-clicked event and seek issue inside region (#3911, #3804)

- src/plugins/spectrogram.ts
Resolves two issues with spectrograms:
* The gain calculation did not seem to be correct.
* A gain of 0 was erroneously replaced by 20
Example of gain issue:
Fixed:
> fix(spectrogram): Fix spectrogram gain calculation

- README.md
Resolves #3677
Add a table of contents for the readme.
> Docs: add ToC

- src/wavesurfer.ts
Resolves #3708
When the audio ends, emit one last `timeupdate` event with the total duration as a parameter.
> Fix: emit final timeupdate on audio end

- src/wavesurfer.ts
Resolves #3963
MediaError errors weren't passed to the error event.
> Fix: pass media error object to error event

- src/plugins/record.ts
I think specifying the device only as options for the microphone is a bit too limited. 
I have the problem that on some devices, noise suppresion is active and there is currently no way to deactivate this with wavesurfer.js recorder plugin. 
Usually it would be done like this: 
```js
navigator.mediaDevices.getUserMedia({
audio: {
autoGainControl: false,
channelCount: 2,
echoCancellation: false,
latency: 0,
noiseSuppression: false,
sampleRate: 48000,
sampleSize: 16,
volume: 1.0
}
});
```
Used the dom type `MediaTrackConstraints` directly instead of a custom type that mimics it partially.
> Accept MediaTrackConstraints when starting mic

- src/plugins/regions.ts
Resolves #
-  implemented `getContent(asHTML:bool)`. it bring possibility to get content as HTML or just String value.
- `region-content-changed`  RegionPlugin event:  It fires always `setContent(value)` is called.
- Create a Region
- Implement `region-content-changed` event on `RegionPlugin`.
- using `region.getContent()` should  bring content value as string.
- passing asHTML param  as true to `region.getContent()` method, it should return HTMLElement string.
- using `region.setContent()` should fires `region-content-changed` event.
-
> getContent method and region-content-changed event created

- cypress/e2e/regions.cy.js
- src/plugins/regions.ts
Right now `region-created`` only triggers when the
user lifts their moust, which means it's not possible
to get any callbacks or events of their selection until
that moment. This new event triggers immediatly, allowing
developers to hook onto events, or do things like change
the color, add a number inside etc..
I created a new event so existing code doesn't break.
> Feat(Regions): Add a `region-initialized` event that triggers early

- src/plugins/hover.ts
- fix unsubscribe handler to remove the `wheel` event listener using the correct callback
- `npm run lint` *(fails: ESLint couldn't find config)*
- `npm test` *(fails: cypress not found)*
> Fix(Hover plugin): wheel listener removal

- src/renderer.ts
Moved the width check condition after it may be changed to 0 if the barWidth or barGap are set in the config.
> fix(renderer): Prevent rendering if the canvas length is 0

- .gitignore
- src/__tests__/timer.test.ts
- src/timer.ts
Resolves #4119
There was an unintended change in timer.ts when adding unit tests. It's now reverted.
> Fix(timer): revert breaking change

- src/renderer.ts
Resolves #4111
I've added % units to appease Firefox.
> Fix(Firefox): add polygon percentage units

- src/event-emitter.ts
- src/player.ts
- src/wavesurfer.ts
Resolves #4128
`setSrc` is now always called but it doesn't set the URL to an empty string.
> Fix: loadBlob URL setting

- src/wavesurfer.ts
Clarify `seekTo` method documentation by replacing "percent" with "ratio" to avoid confusion, as the parameter expects a value in the range [0, 1], not [0, 100].
* Updated the comment for the `seekTo` method in `src/wavesurfer.ts`.
* Changed "percentage" to "ratio" to improve clarity.
* No functional code changes; this is a documentation-only update.
> docs: Replace 'percent' with 'ration' in seekTo's comment for clarity

- src/plugins/regions.ts
Resolves #
After setting a `minLength` for `RegionsPlugin.enableDragSelection`, if create a new region, the dragging operation might stop immediately. This happens because the region's length does **not satisfy** the condition `length >= this.minLength && length <= this.maxLength`. According to the documentation, the `minLength` parameter appears to be primarily intended for resize operations, so it should be avoided during the initial creation.
https://github.com/user-attachments/assets/dab43d3d-17fb-45c2-89b7-d3ab6a4eb49a
> Fix(Regions): region can't be dragged when setting minLength

- src/plugins/regions.ts
Exposes the side that is resized in the `update-end` event. 
My use case is that I want to play the surrounding audio when a side is resized.
I've added `side` to the `update-end` event. 
So you can get the side like this:
```
regions.on('region-updated', (region, side) => {
console.log('Updated region', region)
console.log(side)
})
```
You can try it with yarn start and listen on `update-end`
https://github.com/user-attachments/assets/cd0ad48c-4a35-4d2e-83d0-6462c5cdcea7
> feat(Region): expose resized side on update end
